### ISSUE TITLE
Support for running midje tests

### ISSUE THREAD

**Issue by devth** [liquidz/vim-iced#108]
https://github.com/marick/Midje

**Comment by liquidz** [comment]
@devth Thank you for your proposal!

vim-iced uses `cider-nrepl` for testing, and cider-test requires `clojure.test` protocol.
Unless midje does not provide this protocol, it is difficult to support midle unfortunately.
c.f. https://github.com/marick/Midje/issues/356

BTW you can run midje tests by simply evaluating `facts` or `fact` form with `<Leader>et` or `<Leader>ee`.

**Comment by devth** [comment]
Wow, https://github.com/marick/Midje/issues/356 is a sad state of affairs! Thank you for linking that. Instead I will use something like:

```
    autocmd FileType clojure nmap <buffer> ctm :IcedEval (require 'midje.repl)(midje.repl/load-facts *ns*)<cr>
```

to run my Midje tests. 💥

**Comment by liquidz** [comment]
Oh.. Emidje is cool.
https://github.com/clojure-emacs/cider/commit/030847dae2b90ec540d978087c3e32a3b0b69f9e
https://github.com/nubank/emidje

**Comment by liquidz** [comment]
I'm working with following projects.
* https://github.com/liquidz/kaocha-nrepl
* https://github.com/liquidz/vim-iced-kaocha

**Comment by devth** [comment]
I'd love to test it out when ready.

**Comment by liquidz** [comment]
@devth I'm ready!
Could you try to test vim-iced-kaocha?
https://github.com/liquidz/vim-iced-kaocha

As an attention, kaocha-midje 0.0-5 will run facts every loading facts part in kaocha.
This behavior may fix next version of kaocha-midje.
https://github.com/lambdaisland/kaocha-midje/pull/1

**Comment by devth** [comment]
I followed the instructions but when I try commands like `:IcedKaochaTestNs` I get this in my status bar:

```
: Ran 0 assertions, in 0 test functions. 0 failures, 0 errors.
```

`IcedKaochaTestUnderCursor` gives me:

```
Failed to fetch fact's guid.
```

🤔

**Comment by liquidz** [comment]
@devth Thanks for your testing!

> :IcedKaochaTestNs I get this in my status bar

kaocha has a `ns-patterns` configuration, and its default value is `.*-test`.
So you should specify `ns-patterns` to your tests.edn.

I added sample configuration to README
https://github.com/liquidz/vim-iced-kaocha/commit/eff2786ad40714a096fc709ed192fd0d7fad70ea

> IcedKaochaTestUnderCursor gives me:

Sorry! I fixed the problem!
https://github.com/liquidz/vim-iced-kaocha/commit/7966f332bc0bd5e58fe25fb70cf86b832bbf2baf

Could you try again?

**Comment by devth** [comment]
Thanks! It's working now. In stdout buffer I see:

```
;;
;; Iced Buffer
;;
Run `(doc midje)` for Midje usage.
Testing: :unit
Testing ns(1/1): :yetibot.core.test.commands.duckling
Testing fact(1/5): :yetibot.core.test.commands.duckling/2b30d65b69ad9d10701d1665c27980218fa7ef8a
Testing fact(2/5): :yetibot.core.test.commands.duckling/5326df84da81988d89b9db289a00e321e6846242
Testing fact(3/5): :yetibot.core.test.commands.duckling/54d2df800d3ff4d269b4d19c5265d3a851dba36f
Testing fact(4/5): :yetibot.core.test.commands.duckling/0aa8c8b5cb91f34aa9cce49052dc6cb32115dd22
Testing fact(5/5): :yetibot.core.test.commands.duckling/187c7e68b638ba7700ac61736a8cef67209cc85e
Run `(doc midje-repl)` for descriptions of Midje repl functions.
Testing: :unit
Testing ns(1/1): :yetibot.core.test.commands.duckling
Testing fact(1/1): :yetibot.core.test.commands.duckling/0aa8c8b5cb91f34aa9cce49052dc6cb32115dd22
true
Testing: :unit
Testing ns(1/1): :yetibot.core.test.commands.duckling
Testing fact(1/1): :yetibot.core.test.commands.duckling/0aa8c8b5cb91f34aa9cce49052dc6cb32115dd22
```

1. I noticed it's a little slow. To run `:IcedKaochaTestUnderCursor` takes several seconds, but if I simply evaluate the `fact` form it's only a few 100ms.
2. I wonder how I can improve the output. I'll investigate Midje's reporting features.

**Comment by liquidz** [comment]
@devth

> I noticed it's a little slow.

kaocha-midje 0.0-5 reloads target namespace every testing, and this may be the cause.
https://github.com/lambdaisland/kaocha-midje/pull/1/files#diff-0431c434b89da394419452f13f8d40c3L34
The next version of kaocha-midje may improve speed.

> I wonder how I can improve the output.

Currently output format is fixed.
If you have a customization idea, please open a issue to vim-iced-kaocha repository.

**Comment by liquidz** [comment]
Closed by stale issue.
Feel free to reopen this issue 😃
