### ISSUE TITLE
NullPointerException attempting to load test namespace that uses Midje

### ISSUE THREAD

**Issue by devth** [liquidz/vim-iced#111]
Running `:IcedRequire` on  https://github.com/yetibot/yetibot/blob/master/test/yetibot/test/commands/weather.clj

Results in `null` and in the stdout_buffer it prints:

```
Error printing return value (NullPointerException) at java.io.StringReader/<init> (StringReader.java:50).
null
```

Related: https://github.com/liquidz/vim-iced/issues/108

**Comment by liquidz** [comment]
@devth I couldn't reproduce the problem with following steps.
1. git clone https://github.com/yetibot/yetibot
2. cd yetibot
3. iced repl
4. nvim test/yetibot/test/commands/weather.clj
5. `:IcedConnect`
6. `:IcedRequire`

![2019-03-24 9 45 42](https://user-images.githubusercontent.com/6941/54873443-ac195100-4e19-11e9-870d-924b192cb741.png)

My environment:
* Leiningen 2.9.1 on Java 11.0.2
* NVIM v0.4.0-301-g63cb309e1

**Comment by devth** [comment]
I confirmed it was some nrepl middleware causing the issue. Sorry for the false alarm and thanks for the help figuring it out!
