### ISSUE TITLE
Feature request: eval motion

### ISSUE THREAD

**Issue by devth** [liquidz/vim-iced#113]
`IcedEvalVisual` and friends are nice but would be really nice if I could eval a motion. I'm basically trying to replicate some of fireplace's `cp..` mappings since that's what I've used for years, so e.g. `cpaw` would eval around word, or `cpab` would eval around parens.

**Comment by liquidz** [comment]
@devth vim-iced has a `<Plug>(iced_eval)` action already.
https://liquidz.github.io/vim-iced/vim-iced.html#vim-iced-evaluating

So could you try the following mapping?
```
nmap <buffer> cp <Plug>(iced_eval)
```

**Comment by devth** [comment]
Amazing! Thank you!!

**Comment by devth** [comment]
Would it be possible to eval motion and also print the result to stdout buffer?

**Comment by liquidz** [comment]
@devth How about the combination of eval motion and `:IcedPrintLast` command?
https://liquidz.github.io/vim-iced/vim-iced.html#%3AIcedPrintLast
Default key mapping is `<Leader>ep`.

**Comment by devth** [comment]
That's what I was thinking but I'm not sure how to combine them. Here was one attempt:

```
    autocmd FileType clojure nmap <buffer> c! <Plug>(iced_eval)<Plug>(iced_print_last) 
```

I think `<Plug>` can't be combined this way. Do you know what it would look like?

**Comment by liquidz** [comment]
@devth Sorry!
Because eval motion works asynchronously, the combination won't work well.
I'm considering to add a motion for evaluating and printing.

**Comment by liquidz** [comment]
@devth I added `<Plug>(iced_eval_and_print)` to `dev` branch.
https://vim-iced-nightly.netlify.com/vim-iced.html#%3CPlug%3E%28iced_eval_and_print%29

Could you try this motion?
If it works, I'll release 0.10.4!

**Comment by devth** [comment]
@liquidz works great! Thanks!

**Comment by liquidz** [comment]
@devth Thanks!
I released `0.10.4` ! #120

**Comment by devth** [comment]
Hi @liquidz, what do you think about a command similar to `<Plug>(iced_eval_and_print)` but instead of printing it `tap>`s it? This would be nice in combination with https://github.com/Lokeh/punk, which I'm starting to use.

**Comment by liquidz** [comment]
@devth That's a nice idea!
It may go well with browsing tapped value in vim-iced too.

https://liquidz.github.io/vim-iced/vim-iced.html#vim-iced-debugging-browsing-tapped-values
https://twitter.com/uochan/status/1146982101662572544?s=19

**Comment by liquidz** [comment]
@devth I added `<Plug>(iced_eval_and_tap)`.
https://vim-iced-nightly.netlify.com/vim-iced.html#%3CPlug%3E%28iced_eval_and_tap%29
Could you try `dev` branch?

**Comment by devth** [comment]
@liquidz thanks! I'm using it now - works great so far.
