### ISSUE TITLE
How to use tracing?

### ISSUE THREAD

**Issue by devth** [liquidz/vim-iced#118]
I found `IcedToggleTraceVar` / `IcedToggleTraceNs` in the docs but I'm not sure how to use them. I turned on tracing for the current namespace then evaluated some functions but I'm not seeing any trace output. Where should I expect to see it?

Thanks!

**Comment by liquidz** [comment]
@devth I'm sorry for late reply!
Traced output will be displayed in stdout buffer.
Could you try [:IcedStdoutBufferOpen](https://liquidz.github.io/vim-iced/vim-iced.html#%3AIcedStdoutBufferOpen) command?

**Comment by devth** [comment]
Thanks! What does it do when tracing is on? Does it just capture stdout / logs? Or results from executing functions? I wasn't sure what to expect.

**Comment by liquidz** [comment]
@devth Sorry for less documents.

cider's document is easy to understand.
https://cider.readthedocs.io/en/latest/miscellaneous_features/#tracing-function-execution

**Comment by devth** [comment]
@liquidz thanks for the docs! I didn't realize I should look in CIDER's docs. Now I know :)

Tracing looks amazing but I'm definitely not seeing it in the stoud buffer. I will try again today.

**Comment by liquidz** [comment]
I added a document for tracing function calls.
https://vim-iced-nightly.netlify.com/#_tracing_function_calls
