### ISSUE TITLE
How is skeleton intended to work?

### ISSUE THREAD

**Issue by devth** [liquidz/vim-iced#119]
```
Provides code skeleton when you open new file
```

I created a new .clj file and opened it while connected to iced. Messages shows:

```
|| Connected.
|| (ns ..) form is not found.
```

Do I need to activate it?

**Comment by liquidz** [comment]
@devth I'm sorry for late reply!
vim-iced uses [BufNewFile](https://vim-jp.org/vimdoc-en/autocmd.html#BufNewFile) auto command for generating skeleton.
So you shouldn't create new `.clj` file beforehand.

Could you try following steps?
* Open existing *.clj file (such as core.clj)
* Execute `:IcedConnect`
* Execute `:e non_existing_new.clj` for creating new `.clj` file in vim

**Comment by devth** [comment]
I will try this out! Thank you for the explanation. I am happy to help improve the docs on this project as I go, if you'd like.

And thank you for this amazing plugin! I've switched completely from fireplace to vim-iced and love it. I even used it for a livecoding session a few weeks ago, and will be using it again at Clojure/north this week! The CIDER capabilities are magic 🎇

**Comment by liquidz** [comment]
I'm glad to hear that!
PR is very welcomed!!

**Comment by liquidz** [comment]
I added a document for skeleton
https://vim-iced-nightly.netlify.com/#skeleton

**Comment by devth** [comment]
New docs look amazing. Thanks @liquidz!!
