### ISSUE TITLE
Project misidentified as clojurescript 

### ISSUE THREAD

**Issue by matthias-margush** [liquidz/vim-iced#121]
This line in my deps.edn is causing `iced repl` to misidentify it as a clojurescript file:

```
exclusions [org.clojure/clojurescript]
```

**Comment by liquidz** [comment]
@matthias-margush I'm also think that is a problem.
I'm adding `--without-cljs` option to `dev` branch as a workaround.
https://github.com/liquidz/vim-iced/pull/120/commits/674591bccd64a934eba75f8653faadb3a5ccf10f

But this is not a permanent solution, so I'll seek a better solution.

**Comment by liquidz** [comment]
Closed by #241 

@matthias-margush Sorry for late fixes.
I just added a more accurate check with Babashka.
Babashka is not mandatory,  and `iced` command will use it automatically when bb command exists.
(the accurate check is limited for Leiningen and Clojure CLI for now)
https://liquidz.github.io/vim-iced/#iced_usage

Feel free to reopen this issue if there are some problems :)
