### ISSUE TITLE
Split stdout window vertically

### ISSUE THREAD

**Issue by Fedreg** [liquidz/vim-iced#122]
Hi, can't seem to get the stdout window feature (<Leader>ss) to ever split vertically instead of horizontally.  Have tried several ways to make this default behavior but have failed. Can get my normal splits to default to vertical but not the `vim-iced-stdout-buffer`.

Admittedly, I'm a vim noob and have been working in Emacs for years so if anyone can point me in the right direction I would really appreciate it!

Using neovim 0.3.5

Thanks!!

**Comment by liquidz** [comment]
@Fedreg Could you try to add `let g:iced#buffer#stdout#mods = 'vertical'` to your config file such as `~/.config/nvim/init.vim`?
https://liquidz.github.io/vim-iced/vim-iced.html#g%3Aiced%23buffer%23stdout%23mods

**Comment by Fedreg** [comment]
@liquidz That did it.  Works great.  Thank you!!!
