### ISSUE TITLE
Tab-local scoped iced REPL connection

### ISSUE THREAD

**Issue by devth** [liquidz/vim-iced#124]
I'd like to have multiple REPLs and projects open inside a single vim instance, each in their own tab. Currently it appears the REPL connection is global.

Sometimes global is nice when I want a single REPL across projects, but other times I want each tab to have its own connection.

**Comment by liquidz** [comment]
@devth First, thank you for your feedback!

I have no plan to support managing multiple connections.
This is based on the personal idea that Vim tends not to keep running single instance like Emacs.
(I sometimes restart vim, and start multiple vim also.)

Using tab-local scope variables is seemingly easy in VimScript.
However it make codes so complex in managing caches, nREPL messages, stdout buffers and so on.

In my opinion, it is better to use terminal-multiplexer such as tmux.

**Comment by devth** [comment]
That makes sense, thank you for explaining.

I used to heavily rely on tmux but found it reduced the performance of my terminal on macOS too much, so I've been experimenting with replacing tmux with neovim terminal + tabs the past few months. I'll consider some other alternatives.
