### ISSUE TITLE
Support popup window in Vim8

### ISSUE THREAD

**Issue by liquidz** [liquidz/vim-iced#126]
https://github.com/vim/vim/blob/master/runtime/doc/popup.txt

This may support virtual text and floating window in Vim8.

**Comment by knubie** [comment]
Displaying the definition of a function in a popup/floating window would be neat.

**Comment by liquidz** [comment]
@knubie Thanks for your feedback!
Is it like this? https://twitter.com/uochan/status/1143170332078985216

In my opinion, this is useful for short functions, while long functions may be hard to see on popup/floating window.

**Comment by knubie** [comment]
Yeah! That looks great.

I agree with short vs long functions. Maybe there could be a setting like

```viml
let g:iced_fn_def_popup_max_length = 25
```

If the function is longer than 25 lines, it’s opened in a new split window instead. What do you think?

**Comment by liquidz** [comment]
@knubie I think it is not intuitive that we couldn't know whether it will appear in popup or splitted window until executed.
And also users should be able to select the behavior. (Some people may want to show the source in splitted window always)

In current `dev` branch, vim-iced has two commands to open a function document.
* [IcedDocumentOpen](https://vim-iced-nightly.netlify.com/vim-iced.html#%3AIcedDocumentOpen)
* [IcedPopupDocumentOpen](https://vim-iced-nightly.netlify.com/vim-iced.html#%3AIcedPopupDocumentOpen)

This two commands enable users to select the behavior for opening a function document, and users can know in advance where the document will be appear.

How about preparing two commands like function document?
Any idea is welcome!

**Comment by liquidz** [comment]
@knubie I added [IcedPopupSourceShow](https://liquidz.github.io/vim-iced/vim-iced.html#%3AIcedPopupSourceShow) command to show source code in popup window.
This command will fallback [IcedSourceShow](https://liquidz.github.io/vim-iced/vim-iced.html#%3AIcedSourceShow) if source code is longer than [&lines](https://vim-jp.org/vimdoc-en/options.html#'lines').

**Comment by liquidz** [comment]
Fixed by #125

**Comment by knubie** [comment]
@liquidz The changes sound great!

Unfortunately I wasn't able to get either working. When using `:IcedDocumentOpen` or `:IcedPopupDocumentOpen` on a function it returns "Not found." even when the function is defined in the same namespace.

Using Neovim 0.3.7 and shadow-cljs.

**Comment by liquidz** [comment]
@knubie Thank you for your reporting!
It seems a bug from verion 0.10.5 or earlier.
I created another issue #135
