### ISSUE TITLE
Auto document popup window takes several seconds to appear

### ISSUE THREAD

**Issue by Fedreg** [liquidz/vim-iced#127]
Thanks for pushing up this feature to the Dev branch to play around with!!  Works great.  Only issue is that it takes about 4 seconds for the popup to appear.  I see there is the `g:iced#popup#time` setting for how long before closing (and I even tried toggling that in case it affected the opening behavior) but is there a value I can toggle to make the popup open faster?  General neovim setting maybe?

On the video you posted yours opens up much faster!!  Thanks again!

....BTW, I don't have this issue when using popup windows on the debugger, those open up right away

**Comment by liquidz** [comment]
@Fedreg Thanks for your testing!
Displaying popup document is using `CursorHold` and `CursorHoldI` auto command, so its speed is depended on `updatetime` option.
https://vim-jp.org/vimdoc-en/options.html#'updatetime'

Could you try to add `set updatetime=500` to your config file?

**Comment by Fedreg** [comment]
perfect, thank you!!
