### ISSUE TITLE
Error running iced repl on clojure cli projects

### ISSUE THREAD

**Issue by Fedreg** [liquidz/vim-iced#131]
Hi, `iced repl` works great on Lein projects but when I'm trying to run it on clj projects I get the following error: 
```
grep: /usr/local/bin/../doc/vim-iced.txt: No such file or directory
OK: Clojure CLI project is detected
Error building classpath. Manifest type not detected when finding deps for iced-repl/iced-repl in coordinate #:local{:root "/usr/local"}
``` 
This happens on both clojure and clojurescript projects.  Have tried passing `--force-clojure-cli`.

Using latest master vim-iced on neovim 0.4.0-dev
I'm sure there is some configuration issue on my side but if you can think of any pointers I would appreciate it!

As always, thanks for building this!  Cheers!

**Comment by liquidz** [comment]
@Fedreg Are you sure that 'iced' command file is **copied** to '/usr/local/bin' ?

If you are using `~/.vim/plugged` directory as a plugin directory, you should add `~/.vim/plugged/vim-iced/bin` to your `$PATH`.
* https://github.com/Fedreg/.vimrc/blob/master/vimrc#L11
* https://liquidz.github.io/vim-iced/vim-iced.html#vim-iced-install-command

In clojure cli project, iced command references deps.edn file in `~/.vim/plugged/vim-iced` directory.
So copied iced command file cannot find the 'deps.edn' file.

**Comment by Fedreg** [comment]
@liquidz Thanks!  Yes, `iced` is definitely in `usr/local/bin` and I definitely have `~/.vim/plugged/vim-iced/bin` on my $PATH.   Still get the error though... I'll play around with it a bit this weekend.

**Comment by liquidz** [comment]
@Fedreg Could you delete your `usr/local/bin/iced` while remaining your `$PATH` ?

**Comment by Fedreg** [comment]
@liquidz Not sure I'm understanding... if I delete my `usr/local/bin/iced` I'll get a `command not found: iced` error.   What did you mean by
> remaining your $PATH

thx for the help!

**Comment by liquidz** [comment]
@Fedreg Sorry for my ugly English.
> I definitely have ~/.vim/plugged/vim-iced/bin on my $PATH

You have `~/.vim/plugged/vim-iced/bin` in your `$PATH`, and there should be `~/.vim/plugged/vim-iced/bin/iced`.
So you should not get `command not found`  error even if you delete `/usr/local/bin/iced`.

For example, I have `PATH=$PATH:~/src/github.com/liquidz/vim-iced/bin` in my shell config, and `which` command can detect `iced` command file.
```
$ which iced
/Users/iizuka/src/github.com/liquidz/vim-iced/bin/iced
```

**Comment by Fedreg** [comment]
ahhh... I see what you mean... thanks for clarifying.  I'll see what is going on with my path.   Closing issue.  thanks again!
