### ISSUE TITLE
Can't get it working correctly in neovim, won't auto connect and can't eval

### ISSUE THREAD

**Issue by danielytics** [liquidz/vim-iced#165]
Hi, I'm using Iced with Neovim and followed the instructions, but am having trouble getting it to work.

I run `iced repl` and this runs ok. I then open a clojure file in vim, but it doesn't automatically connect. I can use `:IcedConnect` and it says `connected`, but I can't eval anything, it just says `cannot resolve symbol` for everything. For example, if I type `(println "Hello, world")`, place the cursor somewhere inside that form and press <Leader>ee it says `Unable to resolve symbol: println in this context`. I don't get any errors on startup or on connection.

I'm using neovim `0.4.3`, the latest vim-iced from git and leiningen and have the profiles.clj set up as per the instructions.

Any hints as to what I might be doing wrong appreciated.

**Comment by liquidz** [comment]
@danielytics Thanks for your reporting!

> I run iced repl and this runs ok. I then open a clojure file in vim, but it doesn't automatically connect.

vim-iced will connect to REPL automatically when evaluating codes.
But it seems not to work correctly in current latest, so I'll fix it soon!

If you'd like to connect automatically when vim opend `*.clj` files, you can use `VimEnter` autocmd.

* `/path/to/your/.vim/ftplugin/clojure.vim`
```
aug MyVimIcedSetting
  au!
  au VimEnter * call iced#nrepl#auto_connect()
aug END
```

> but I can't eval anything, it just says cannot resolve symbol for everything.

This behavior may depend on your `init-ns` setting in project.clj.

If you open a file which is not `init-ns`, you should do `:IcedRequire` to enter the namespace.
This is a problem only for the first time when opening Vim, and does not cause a problem when moving to other buffers.

However, it's just a hard-to-understand problem, so I'll fix it in the next release.

**Comment by liquidz** [comment]
@danielytics I fixed in [dev](https://github.com/liquidz/vim-iced/tree/dev) branch.
Could you try `dev` branch?

**Comment by danielytics** [comment]
@liquidz Yes, that works! Thank you very much :heart:
