### ISSUE TITLE
<Plug>(iced_eval_and_print) regression in 0.14.0

### ISSUE THREAD

**Issue by nbardiuk** [liquidz/vim-iced#174]
`<Plug>(iced_eval_and_print)` does not print result to output buffer and to virtual text. I receive no feedback about evaluation result.

**Comment by liquidz** [comment]
@nbardiuk Thanks for your reporting!
Sorry for regression. I fixed in on `master` branch.

**Comment by nbardiuk** [comment]
I've just tested, it works form me now. Thank you!

**Comment by liquidz** [comment]
Released by #181
