### ISSUE TITLE
Enable to choose `cli` or `clojure` on Clojure CLI project

### ISSUE THREAD

**Issue by micheam** [liquidz/vim-iced#179]
Current iced command issues a fixed `clj` command when it detects a Clojure CLI project.

However, for certain use cases, it is desirable to launch without readline support.

For example, if I want to run [rebel-readline](https://github.com/bhauman/rebel-readline) in `iced repl`, it will interfere with readline of` clj` command. In this case, it is desirable that the iced command internally issue the `clojure` command.

**Comment by liquidz** [comment]
Closed by #181
