### ISSUE TITLE
Evaluation of last evaluated s-expr

### ISSUE THREAD

**Issue by Cnly** [liquidz/vim-iced#197]
Is it possible to add a feature like `cider-eval-last-sexp` that evaluates the last evaluated s-expression again?

**Comment by liquidz** [comment]
@Cnly Currently can't.
But I have a plan to import a [Conjure](https://github.com/Olical/conjure)'s feature that enables evaluating at [mark](https://vim-jp.org/vimdoc-en/motion.html#mark-motions).
This feature will enable evaluating last s-expression.

**Comment by Cnly** [comment]
@liquidz Thank you, that sounds really exciting. Please feel free to close this issue if that's the case.

**Comment by liquidz** [comment]
@Cnly  I just implemented `IcedEvalAtMark` and `IcedEvalLastOuterTopList` commands experimentally in `dev` branch. (Currently no documents)

If you have some marks, you can evaluate the code by `<Leader>ea` + any key.
E.g. Mark `m` on any position by typing `mm`, then `<Leader>eam` will evaluate it.

`IcedEvalLastOuterTopList` is a little bit limited.
When you use `:IcedEvalOuterTopList` or type `<Leader>et`, vim-iced will mark the position with `g:iced#eval#mark_at_last`. (Default mark is a `1` which can use globally)
Then running `IcedEvalLastOuterTopList` command or typing `<Leader>el` will evaluate the last evaluated s-expression again.

**Comment by Cnly** [comment]
@liquidz Thanks for your work! Just did some quick testing and found maybe this line in `iced#repl#eval_at_mark` is executing the wrong function?

https://github.com/liquidz/vim-iced/blob/cda423540fd328f5e0d51f000eb3d6c205ba5993/autoload/iced/repl.vim#L78

**Comment by liquidz** [comment]
@Cnly Thanks for your testing!
It is right function because we would like to evaluate the form where the cursor is moved.

**Comment by Cnly** [comment]
But doesn't that mean if I put a mark on a form that's not in the top level, `:IcedEvalAtMark` will still execute the top level form that encloses my mark instead?

**Comment by liquidz** [comment]
@Cnly Ah, I see.
I only tested evaluation of top level form yet.
I'll have a look. Thanks!

**Comment by liquidz** [comment]
@Cnly I fixed in `dev` branch ;)

**Comment by Cnly** [comment]
@liquidz Great, I can confirm that. :) But--not sure if it's only my use case--now there seems to be no way to mark a single element (e.g. a variable) in a form and execute it repeatedly. Does that sound like a desirable feature?

**Comment by liquidz** [comment]
@Cnly hmm, I couldn't imagine the use case.

It doesn't make sense to evaluate a single element in a form repeatedly unless it's a global and mutable variable.

Could you tell me the use case you would like to do?

**Comment by Cnly** [comment]
@liquidz Okay, I reconsidered about this and it indeed seems the case is pretty rare except for what you've mentioned. Evaluating forms should be enough. Thanks :)

**Comment by liquidz** [comment]
@Cnly Thanks for your confirmation!
I'll cut a new release this weekend :)

**Comment by liquidz** [comment]
@Cnly It's a little late, but I just released!
Closed by #204
