### ISSUE TITLE
Can't use zprint

### ISSUE THREAD

**Issue by jcpsantiago** [liquidz/vim-iced#199]
I'm using Neovim v0.4.3 on MacOS Catalina. Changed the formatter to `zprint`, accepted to install it and then get an error when trying to use it wither `==` or `=G`:

`function <SNR>117__worker[12]..<SNR>116__publish, line 8`

this is my Neovim config:

```
" Plugins will be downloaded under the specified directory.
call plug#begin('~/.vim/plugged')

" Declare the list of plugins.
Plug 'tpope/vim-sensible'

" Clojure
Plug 'tpope/vim-sexp-mappings-for-regular-people', 	{'for': 'clojure'}
Plug 'guns/vim-sexp',    				{'for': 'clojure'}
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-surround'
Plug 'eraserhd/parinfer-rust', {'do': 'cargo build --release'}
Plug 'liquidz/vim-iced', 				{'for': 'clojure'}

" Autocomplete
Plug 'prabirshrestha/asyncomplete.vim'
Plug 'liquidz/vim-iced-asyncomplete', {'for': 'clojure'}

" Linting
Plug 'dense-analysis/ale'

" UI
Plug 'itchyny/lightline.vim'
Plug 'yggdroot/indentline'
Plug 'yuttie/comfortable-motion.vim'
Plug 'arcticicestudio/nord-vim'
Plug 'dracula/vim'

" Filesystem
Plug 'preservim/nerdtree'

" Version control
Plug 'airblade/vim-gitgutter'
Plug 'itchyny/vim-gitbranch' 

" Utils
Plug 'farmergreg/vim-lastplace'
Plug 'tpope/vim-commentary'
Plug 'mechatroner/rainbow_csv'

" List ends here. Plugins become visible to Vim after this call.
call plug#end()

" Enable vim-iced's default key mapping
" This is recommended for newbies
let g:iced_enable_default_key_mappings = v:true

" Autocomplete with TAB
inoremap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
inoremap <expr> <cr>    pumvisible() ? "\<C-y>" : "\<cr>"


" Auto-reload file changes
set autoread

set termguicolors
set number
set cursorline
set updatetime=100
set noshowmode

set undodir=~/.vim/undo
set undofile

colorscheme nord

" set theme for lightline
let g:lightline = { 
	\ 'colorscheme': 'nord',
      	\ 'active': {
      	\   'left': [ [ 'mode', 'paste' ],
      	\             [ 'gitbranch', 'readonly', 'filename', 'modified' ] ],
	\   'right': [ ['percent'],
	\              [],
	\	       ['filetype'] ],
	\},
	\ 'component_function': {
      	\ 'gitbranch': 'gitbranch#name'
      	\ }}

" set Ctrl + N to toggle NERDtree
map <C-n> :NERDTreeToggle<CR>

" add highlight to 81st character
highlight ColorColumn ctermbg=magenta
call matchadd('ColorColumn', '\%81v', 100)

" for code linting
let g:ale_linters = {'clojure': ['clj-kondo']}
let g:iced_formatter = 'zprint'
```

I'm new to Vim. Let me how can I help you help me :)

**Comment by liquidz** [comment]
@jcpsantiago Thanks for your reporting!

I couldn't reproduce the problem in my environment.

It may be the effect of other plugins,                                                                                                                                                                     so could you try to delete `~/.vim/plugged/vim-iced/bin/zprint-clj` and use [minimal configuration](https://liquidz.github.io/vim-iced/#minimal_configuration)?

**Comment by jcpsantiago** [comment]
Works fine with the minimal configuration. Which means it could be one of the plugins. I'll `PlugClean` everything and then add the plugins back one by one and report back ;)

**Comment by jcpsantiago** [comment]
Seems I tracked it down to this `let g:iced_enable_default_key_mappings = v:true`
If I add it to the minimal configuration, I get the a prompt asking to install `zprint` after pressing `=G` that ends with `Press ENTER or type command to continue` followed by `function <SNR>45__worker[12]..<SNR>44__publish, line 8`.

If I remove that line and press `=G` all code is indendent, but neovim never asks to install `zprint`

**Comment by liquidz** [comment]
@jcpsantiago 
vim-iced hooks `==` and `=G` for custom formatting.
https://github.com/liquidz/vim-iced/blob/master/ftplugin/clojure.vim#L545-L551

So when you disable default key mappings, `nvim` will use default a formatter or other plugin's one. (may be `vim-sexp`'s formatter)

**Comment by jcpsantiago** [comment]
I see. So yes it's probably using `vim-sexp` instead of whatever I choose for `vim-iced`. 

BTW I just tested using `cljstyle` and the same thing happens, same error message: `function <SNR>131__worker[12]..<SNR>130__publish, line 8`

**Comment by liquidz** [comment]
Feel free to reopen ☺️
