### ISSUE TITLE
Issue with debugger in Neovim

### ISSUE THREAD

**Issue by Fedreg** [liquidz/vim-iced#208]
Hi, loving iced but having an odd issue with the debugger...

The debugging values display correctly in the popup window but the highlighting is incorrect.  Instead of highlighting each form of the fn being debugged, the lowest function on the screen is constantly highlighted instead.   (See recording)

Most likely something with my setup...  any ideas?

nvim v 4.3
latest iced master
nrepl 0.6.0

Thx!!!

![Screen-Recording-2020-04-15-at-4](https://user-images.githubusercontent.com/17401067/79324488-55bffa00-7ed5-11ea-8d34-b4fd6646468f.gif)

**Comment by Fedreg** [comment]
Apologies.. just saw your note on `minimal configuration` in another issue... Tried that and the debugger works fine with that config.   Must be another plugin interfering.   If you have any idea what might cause it, please let me know.. Otherwise I'll take the painful approach and figure it out.

My plugins: 
```
Plug 'clojure-vim/async-clj-omni',       {'for': 'clojure'}
Plug 'elmcast/elm-vim'
Plug 'guns/vim-sexp',                    {'for': 'clojure'}
Plug 'junegunn/fzf',                     { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'iamcco/markdown-preview.nvim',     { 'do': { -> mkdp#util#install() } }
Plug 'liquidz/vim-iced',                 {'for': 'clojure'}
Plug 'liquidz/vim-iced-coc-source',      {'for': 'clojure'}
Plug 'morhetz/gruvbox'
Plug 'neoclide/coc.nvim',                {'branch': 'release'}
Plug 'preservim/nerdtree'
Plug 'scrooloose/nerdcommenter'
Plug 'sjl/gundo.vim'
Plug 'tpope/vim-dadbod'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-sensible'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'ifightcrime/Muon'
```
thx!!!

**Comment by liquidz** [comment]
@Fedreg Thanks for your reporting!
Hmm, I have no idea about other plugin's influences.

BTW, do you have the same problem when you evaluate `myfn` again?
`myfn`'s metadata may be outdated.

**Comment by Fedreg** [comment]
@liquidz No prob, maybe someone else will find it useful...

Yes, same results on every `myfn` eval.

Thx!!

**Comment by Fedreg** [comment]
Disabled all of my plugins except for `iced` and `sexp`.  Still had the issue.

Turns out it is this line causing the issue. 
```
let g:iced_enable_default_key_mappings = v:true
```
Some mapping must be interfering with another one of my settings.   

Have a pretty minimal config but will see if an option is colliding

**Comment by liquidz** [comment]
@Fedreg Sorry, I missed your last comment.
Is the problem solved?

**Comment by Fedreg** [comment]
@liquidz no prob!  I still have the issue but just haven’t had a chance to look into it.   Disabling the keybindings makes it work fine so im sure i can find the cause once I get a sec to dig deeper.

Not a big deal.  Thx for checking though!
