### ISSUE TITLE
Babashka REPL connection only works momentarily

### ISSUE THREAD

**Issue by spieden** [liquidz/vim-iced#211]
## Versions

* Babashka v0.0.93
* Iced v1.4.2
* nvim v0.4.3 (via homebrew)
* Debian 9.12 (inside crostini ChromeOS VM)

## Repro

* Open new buffer
* Run `:IcedInstantConnect babashka`
* Evaluate some forms and move around for 5-20 seconds
* Notice the error `Unexpected error: 'vital: Async.Promise: Timeout'` eventually appears and evaluations stop working

This is an awesome project!

## nvim init.vim

```
let mapleader = "."
let maplocalleader = ","

colorscheme flattened_dark

call plug#begin('~/.vim/plugged')

Plug 'jlanzarotta/bufexplorer', {'tag': 'v7.4.21'}
Plug 'preservim/nerdtree', {'tag': '6.7.9'}

Plug 'kien/rainbow_parentheses.vim'

Plug 'guns/vim-sexp', {'for': 'clojure'}
Plug 'guns/vim-clojure-static'
Plug 'guns/vim-clojure-highlight'

Plug 'tpope/vim-sexp-mappings-for-regular-people'

Plug 'ctrlpvim/ctrlp.vim'

Plug 'neoclide/coc.nvim', {'branch': 'release'}

Plug 'liquidz/vim-iced', {'for': 'clojure'}
Plug 'liquidz/vim-iced-coc-source', {'for': 'clojure'}

call plug#end()

let g:iced_enable_default_key_mappings = v:true
```

**Comment by liquidz** [comment]
@spieden Thanks for your reporting!

I've never had any such problems in my daily use.
Could you tell me your detailed environments (OS, vim/nvim, its version) ?

**Comment by liquidz** [comment]
@spieden I tested vim `8.2.717` and nvim `0.4.3` with the file below, and I couldn't reproduce the problem.
```terminal
$ cat <<EOF > foo.clj
(comment (apply + (range 100)))
EOF

$ vim foo.clj
```
If possible, could you also show me the source file and your `.vimrc` ?

**Comment by spieden** [comment]
I added my version info, but of course now I can't get a repro! It must have been specific to the file I was working with, which I didn't hold onto. 😞 I'll let you know if I hit it again.

**Comment by liquidz** [comment]
Thanks! Feel free to reopen.
