### ISSUE TITLE
send large return values to Stdout buffer?

### ISSUE THREAD

**Issue by tomgeorge** [liquidz/vim-iced#219]
First off, this plugin is amazing :grin: 

I've been working on some code that returns pretty large amounts of data, more than enough to be cut off on the command line.  It also looks like the eval code in `iced#nrepl#eval#out` shortens the output and adds `...`.  

Outside of `set cmdheight=100`, is there a way I can send that data to the Stdout buffer, or perhaps back to the `iced repl` process?  I think this is what `IcedPrintLast` is supposed to do, but for some reason it doesn't work for me.

**Comment by liquidz** [comment]
@tomgeorge I'm sure that stdout buffer is not good for displaying large data.

Could you try to use `tap>` and `IcedBrowseTapped` ?
https://liquidz.github.io/vim-iced/#_browsing_tapped_values

> I think this is what IcedPrintLast is supposed to do, but for some reason it doesn't work for me.

When I tried to evaluate the following code and run `IcedPrintLast`, it took too long time, but result is displayed 😓 
```clojure
(-> "https://clojuredocs-edn.netlify.com/export.compact.edn"
    slurp
    clojure.edn/read-string)
```

**Comment by liquidz** [comment]
It also may be useful to use vim-iced-fern-debugger.
https://github.com/liquidz/vim-iced-fern-debugger#tapped-values

**Comment by tomgeorge** [comment]
I'm not sure what I was missing, but `IcedPrintLast` is working for me now.  Thanks, I will close.

**Comment by Cnly** [comment]
> When I tried to evaluate the following code and run IcedPrintLast, it took too long time, but result is displayed 😓

I also tried to evaluate a form that returns something really long recently, and neovim just stopped responding :/ It took me a long time to figure out what the problem was. Perhaps it'll be better to at least have a way to warn the user about what is going to happen?

**Comment by liquidz** [comment]
@Cnly Thanks for your comment.

> Perhaps it'll be better to at least have a way to warn the user about what is going to happen?

You are right. I should be.
I'll fix it!

**Comment by liquidz** [comment]
Branched to #242
