### ISSUE TITLE
Support defining mappings with LocalLeader

### ISSUE THREAD

**Issue by uosl** [liquidz/vim-iced#229]
I love the keybindings but many of them conflict with ones I've configured myself. What do you think about having a `g:iced_enable_default_key_mappings` you can set to enable the key mappings, just using `<LocalLeader>` instead of `<Leader>`?

**Comment by liquidz** [comment]
@uosl Oh, sorry for late reply.
I missed notification😓 

> What do you think about having a g:iced_enable_default_key_mappings you can set to enable the key mappings, just using <LocalLeader> instead of <Leader>?

I think that's a good option to have.
How about to have a `g:iced_default_key_mapping_prefix` option?
The default value is '<Leader>' and you could change any prefix.

**Comment by liquidz** [comment]
`prefix` may be confusing on some mappings which is not containing `<Leader>`...
https://github.com/liquidz/vim-iced/blob/2.0.0/ftplugin/clojure.vim#L468

`g:iced_default_key_mapping_leader` ?

**Comment by liquidz** [comment]
@uosl I'm working to support on `support-localleader` branch.
https://github.com/liquidz/vim-iced/tree/feature/support-localleader

Could you try to set `let g:iced_default_key_mapping_leader = '<LocalLeader>'`?

**Comment by uosl** [comment]
I just tested your branch and `let g:iced_default_key_mapping_leader = '<LocalLeader>'` works.

Thank you so much for implementing this quickly! :tada:
I also think this approach and naming is great as well.

**Comment by liquidz** [comment]
@uosl Thanks for your confirmation!

**Comment by liquidz** [comment]
Closed by #233
