### ISSUE TITLE
Make map formattable

### ISSUE THREAD

**Issue by liquidz** [liquidz/vim-iced#239]
`Failed to find code` for now

**Comment by liquidz** [comment]
Closed by #245

**Comment by frankitox** [comment]
Nice, thanks :smile:! This one has been bothering me for quite some time.

**Comment by frankitox** [comment]
Hi! I'm getting this error while loading vim

![image](https://user-images.githubusercontent.com/1985577/90321796-7f406f00-df23-11ea-9d93-b4aff3f756f2.png)

I fix it by adding `let g:iced_formatter = 'default'` to my `~/.vimrc`.

**Comment by liquidz** [comment]
@frankitox Oh, I forgot to initialize the variable. Thanks!

I'll fix soon.

**Comment by liquidz** [comment]
@frankitox I just fixed.
Could you try the latest version?

**Comment by frankitox** [comment]
Just did, works correctly :+1:

**Comment by liquidz** [comment]
Thanks for your confirmation!
