### ISSUE TITLE
Freeze vim/nvim when too large values are returned

### ISSUE THREAD

**Issue by liquidz** [liquidz/vim-iced#242]
Branched from https://github.com/liquidz/vim-iced/issues/219#issuecomment-669295835

> > When I tried to evaluate the following code and run IcedPrintLast, it took too long time, but result is displayed 😓

> I also tried to evaluate a form that returns something really long recently, and neovim just stopped responding :/ It took me a long time to figure out what the problem was. Perhaps it'll be better to at least have a way to warn the user about what is going to happen?

**Comment by liquidz** [comment]
@Cnly I'm fixing on `feature/warn-too-long` branch.

It's work in progress, but the warning should be displayed.

And I also added `g:iced#nrepl#skip_evaluation_when_buffer_size_is_exceeded` option to skip evaluation when the nREPL response length exceed `g:iced#nrepl#buffer_size`.
This option can avoid to freeze vim/nvim.

**Comment by Cnly** [comment]
@liquidz Just had a quick test and they worked. Thanks!

PS: There's a typo in the warning message:

> It will ~took~take too long time because evaludated values are too large.

**Comment by liquidz** [comment]
> PS: There's a typo in the warning message:

Oh! Thanks!

**Comment by liquidz** [comment]
@Cnly Just released `2.1.3`. Thanks for your confirmation!

Closed by #243
