### ISSUE TITLE
Can't set up vim-iced with clojurescript

### ISSUE THREAD

**Issue by Risto-Stevcev** [liquidz/vim-iced#250]
I can't set it up for figwheel-main or shadow-cljs (#249) 🙁 

For figwheel-main, I'm going through these steps:

1.`lein new figwheel-main acme-figwheel-app`

And then:
2. `lein fig:build` -- browser shows it as 'Connected'
3. Tried `:IcedConnect` but it can't find `.nrepl-port`

Since that didn't work, then I tried:
2. ` ~/.local/share/nvim/plugged/vim-iced/bin/iced repl --with-cljs`
3. `:IcedConnect` connected, and then `:IcedStartCljsRepl figwheel-main dev` started to load figwheel in the repl. It opened the browser at `http://localhost:9500`. After loading for a minute, it showed 'Connected', but then abruptly fails. This is the output from the inspector:

```
This text is printed from src/acme_figwheel_app/core.cljs. Go ahead and edit it and see reloading in action. core.cljs:198:23
 [goog.net.WebSocket] Opening the WebSocket on ws://localhost:9500/figwheel-connect?fwprocess=77b9c1&fwbuild=dev&fwsid=2bce8842-1a9c-4db5-b100-2b1a5d23f0ee <empty string> console.js:218:20
 [goog.net.WebSocket] WebSocket opened on ws://localhost:9500/figwheel-connect?fwprocess=77b9c1&fwbuild=dev&fwsid=2bce8842-1a9c-4db5-b100-2b1a5d23f0ee <empty string> console.js:218:20
 [Figwheel REPL] Session ID: 2bce8842-1a9c-4db5-b100-2b1a5d23f0ee <empty string> console.js:218:20
 [Figwheel REPL] Session Name: Lucien <empty string> console.js:218:20
 [goog.net.WebSocket] The WebSocket on ws://localhost:9500/figwheel-connect?fwprocess=77b9c1&fwbuild=dev&fwsid=2bce8842-1a9c-4db5-b100-2b1a5d23f0ee closed. <empty string> console.js:218:20
 [goog.net.WebSocket] The WebSocket disconnected unexpectedly: undefined <empty string> console.js:218:20
 [goog.net.WebSocket] Seconds until next reconnect attempt: 1 <empty string> console.js:218:20
 [goog.net.WebSocket] Opening the WebSocket on ws://localhost:9500/figwheel-connect?fwprocess=77b9c1&fwbuild=dev&fwsid=2bce8842-1a9c-4db5-b100-2b1a5d23f0ee <empty string> console.js:218:20
Firefox can’t establish a connection to the server at ws://localhost:9500/figwheel-connect?fwprocess=77b9c1&fwbuild=dev&fwsid=2bce8842-1a9c-4db5-b100-2b1a5d23f0ee. websocket.js:60:22
 [goog.net.WebSocket] An error occurred: undefined <empty string> console.js:218:20
 [goog.net.WebSocket] The WebSocket on ws://localhost:9500/figwheel-connect?fwprocess=77b9c1&fwbuild=dev&fwsid=2bce8842-1a9c-4db5-b100-2b1a5d23f0ee closed. <empty string> console.js:218:20
 [goog.net.WebSocket] The WebSocket disconnected unexpectedly: undefined <empty string> console.js:218:20
 [goog.net.WebSocket] Seconds until next reconnect attempt: 2 <empty string> console.js:218:20
 [goog.net.WebSocket] Opening the WebSocket on ws://localhost:9500/figwheel-connect?fwprocess=77b9c1&fwbuild=dev&fwsid=2bce8842-1a9c-4db5-b100-2b1a5d23f0ee <empty string> console.js:218:20
```

The page is no longer available on refresh

Since that didn't work, then I tried:

2. `lein fig`
And that opens the page, but it just hangs on `Opening URL http://localhost:9500` and never connects. I'm guessing that's a figwheel-main issue unless there's something specific I'm supposed to do on that step

**Comment by liquidz** [comment]
@Risto-Stevcev Thanks!

At first, `lein fig:build` will not launch nREPL server.
> 2. lein fig:build -- browser shows it as 'Connected'
> 3. Tried :IcedConnect but it can't find .nrepl-port

So the following steps are the right way.
> 2. ~/.local/share/nvim/plugged/vim-iced/bin/iced repl --with-cljs
> 3. :IcedConnect connected, and then :IcedStartCljsRepl figwheel-main dev 

And I could reproduce the problem (but I'm using figwheel-main at work, and didn't get such errors).
I'll try to fix it.

BTW current workaround is here.
* Execute `:IcedQuitCljsRepl` after WebSocket disconnected
* Execute  `:IcedStartCljsRepl figwheel-main dev` again

**Comment by liquidz** [comment]
@Risto-Stevcev I'm sorry it took so long.
This problem shoud be fixed in ver `2.1.9`.

Could you try the latest version?

**Comment by Risto-Stevcev** [comment]
@liquidz Nice it's working now :slightly_smiling_face: 
Why does vim-iced use a custom repl? thinking in comparison to cider

**Comment by liquidz** [comment]
@Risto-Stevcev Thanks for your confirmation!

> Why does vim-iced use a custom repl? thinking in comparison to cider

What "custom repl" mean?
In my recognition, CIDER starts customized REPL (injecting dependencies and middlewares) inside Emacs via cider-jack-in.

vim-iced provides the way to start REPL outside Vim, so what we are doing is basically the same.

**Comment by Risto-Stevcev** [comment]
Ah ok, sorry I'm not too familiar with Cider -- I saw your comment about jack-in
