### ISSUE TITLE
Unable to get working with figwheel-main and deps.edn

### ISSUE THREAD

**Issue by uosl** [liquidz/vim-iced#253]
You can reproduce with the following `deps.edn`
```
{:paths ["src"]
 :deps {org.clojure/clojure {:mvn/version "1.10.1"}
        org.clojure/clojurescript {:mvn/version "1.10.773"}}
 :aliases {:dev {:extra-paths ["target" "resources"]
                 :extra-deps {com.bhauman/figwheel-main {:mvn/version "0.2.11"}}}}}
```
`dev.cljs.edn`
```
{:main foo.core}
```
and `src/foo/core.cljs`
```
(ns foo.core)

(js/alert "Hello")
```
Using figwheel-main directly works as expected with `clj -A:dev -m figwheel.main -b dev -r`. But I haven't figure out how to evaluate ClojureScript code from vim-iced using this setup. I've tried
```
iced repl -A:dev --with-cljs
:IcedStartCljsRepl figwheel-main dev
```
and it starts figwheel.main, opens a browser page and runs my code, but then it immediately shuts down (reloading the page gives "Unable to connect"). Evaluating cljs code gives either no response or "Not connected".

**Comment by liquidz** [comment]
@uosl Is this similar to this issue?
https://github.com/liquidz/vim-iced/issues/250

How about this workaround?
https://github.com/liquidz/vim-iced/issues/250#issuecomment-676136350

**Comment by uosl** [comment]
It might be similar, although that issue is with leiningen instead of deps.edn.

I tried the workaround, but nothing happens when running `:IcedStartCljsRepl figwheel-main dev` again.

**Comment by liquidz** [comment]
@uosl Thanks!
I could reproduce the problem.

BTW, the following workaround worked well in my environment, so I assume that this is the same cause as #250.

1. Execute `:IcedStartCljsRepl figwheel-main dev` (first time)
   * Browser opens new tab, and alerts "hello".
   * Then disconnected suddenly.
1. Execute `:IcedQuitCljsRepl`
   * Opened tab in browser is still there.
1. Execute `:IcedStartCljsRepl figwheel-main dev` again
   * No new tab is opened, but existing tab will be changed to `Connected`.

**Comment by liquidz** [comment]
@uosl I tweaked starting cljs-repl steps with figwheel-main, and pushed codes to `dev` branch.
It seems work well in my environment.

Could you try `dev` branch?

**Comment by uosl** [comment]
You are right! I managed to get it working like you described in the workaround now.

Thank you, this should keep me afloat until you get around to fixing it. [=

*Seems like you've already done it while I was typing this; I'll test the branch now!*

**Comment by uosl** [comment]
I tested the dev branch and it works perfect now; no disconnection after the first IcedStartCljsRepl.

Thank you! :tada:

**Comment by liquidz** [comment]
Thanks for your confirmation!

**Comment by liquidz** [comment]
Merged to master https://github.com/liquidz/vim-iced/pull/254
