### ISSUE TITLE
Add a way to inject dependencies at jack-in

### ISSUE THREAD

**Issue by Risto-Stevcev** [liquidz/vim-iced#258]
Cider has a cool feature to inject the nrepl deps at jack-in (`cider-inject-dependencies-at-jack-in`+`cider-jack-in-cljs`), it would be nice to have a similar feature for iced :slightly_smiling_face:

**Comment by liquidz** [comment]
Does this command help you?
https://liquidz.github.io/vim-iced/vim-iced.html#%3AIcedJackIn

**Comment by Risto-Stevcev** [comment]
Ah thanks!
