### ISSUE TITLE
completion via completion-nvim?

### ISSUE THREAD

**Issue by tami5** [liquidz/vim-iced#259]
Hay there, I read somewhere that vim-iced support omnifunc, I don't know how to set it up or if it will work with completion framework such as completion-nvim. I use nvim_lsp and I set my omnifunc like this:

omnifunc=v:lua.vim.lsp.omnifunc

any thought will be extermlly helpful, thanks

**Comment by liquidz** [comment]
Yes, vim-iced supports omnifunc.
- https://liquidz.github.io/vim-iced/#omni_completion
- https://github.com/liquidz/vim-iced/blob/2.2.0/ftplugin/clojure.vim#L296

I have never used completion-nvim, so I don't know how to set it up for now.
Maybe we need an external source as follows?
- https://github.com/liquidz/vim-iced-asyncomplete
- https://github.com/liquidz/vim-iced-coc-source

**Comment by tami5** [comment]
Thanks a lot
