### ISSUE TITLE
syntax highlighting in markdown docs <leader>hc

### ISSUE THREAD

**Issue by tami5** [liquidz/vim-iced#260]
Hi there I'm consuming so much of hc feature, however, the syntax highlighting just won't work for me, I use tpope markdown plugin and I added:

```viml
let g:markdown_fenced_languages = ['html', 'python', 'bash=sh', 'clojure', 'clj=clojure', 'sql', 'js=javascript']
```

Still it won't work, so I installed guns/vim-clojure-static, but still the issue isn't fixed.

BTW: It doesn't work for markdown files, so I understand if this issue isn't relative to vim-iced.

Thanks

**Comment by liquidz** [comment]
In my environment, it seems work well 🤔 
<img width="691" alt="2020-09-14 6 15 44" src="https://user-images.githubusercontent.com/6941/93028890-06335500-f652-11ea-86ba-e4406a19f02f.png">

I confirmed with nvim 0.4.4 and following settings.

```vim
if &compatible
  set nocompatible
endif
set runtimepath+=~/.cache/dein/repos/github.com/Shougo/dein.vim

if dein#load_state('~/.cache/dein')
  call dein#begin('~/.cache/dein')

  call dein#add('~/.cache/dein/repos/github.com/Shougo/dein.vim')
  call dein#add('guns/vim-sexp', {'on_ft': 'clojure'})
  call dein#add('liquidz/vim-iced', {'on_ft': 'clojure'})
  call dein#add('tpope/vim-markdown')

  call dein#end()
  call dein#save_state()
endif

filetype plugin indent on
syntax enable

let g:markdown_fenced_languages = ['html', 'python', 'bash=sh', 'clojure', 'clj=clojure', 'sql', 'js=javascript']
```

**Comment by tami5** [comment]
I guess its a problem with neovim 0.5, Thanks a lot for confirming that its an issue on my side.
