### ISSUE TITLE
Slows down basic operations

### ISSUE THREAD

**Issue by b-ryan** [liquidz/vim-iced#263]
Hi there,

I love this plugin so far, thanks for working on it.

I have noticed that vim-iced appears to be responsible for slowing down some basic operations. For example, just using `o` to start a new line takes several seconds.

This appears to be related to vim-sexp, however I don't have this problem when I only use vim-sexp. If I disable the vim-sexp plugin, this problem goes away.

Steps to reproduce:

- Enable vim-sexp and vim-iced
- `:IcedConnect`
- Edit code like this

```clojure
(prn ;; cursor here in normal mode, press o
 (+ 3 4)
  (+ 1 2))
```

With a file only containing the above code, the delay is small, but I still notice one. The problem is much worse in a bigger project.

**Comment by liquidz** [comment]
vim-iced provides auto indentation feature by default.
https://liquidz.github.io/vim-iced/vim-iced.html#vim-iced-indenting

If you didn't customize formatters, `cljfmt` will be used and this is little bit slow.
https://liquidz.github.io/vim-iced/#formatting_customize

So you can do one of the following.
* Disable auto indentation
  * `let g:iced_enable_auto_indent = v:false`
* Use custom formatter
  * I'm using [cljstyle](https://github.com/greglook/cljstyle)

**Comment by b-ryan** [comment]
Thanks for the quick reply! I disabled the auto indentation and that worked. It might help if the word "slow" or "delay" were in the help docs, I had searched there before opening the issue.

Thanks again

**Comment by liquidz** [comment]
Thanks! I'll update documents.
