### ISSUE TITLE
CommandPalette hides command message

### ISSUE THREAD

**Issue by nbardiuk** [liquidz/vim-iced#264]
When a command is called from Command Palette the echo message from the command is not visible to the user

Steps to reproduce:
 * :IcedCommandPalette
 * Connect

Expected:
 * a `Connected` message 

Actual:
 * no message is displayed (although it is present in `:messages`)

I am using `fzf` for candidates selection

**Comment by liquidz** [comment]
@nbardiuk Sorry for late reply, and thanks for your reporting!

It seems to depend on `cmdheight` setting.
when `set cmdheight=1` no messages is displayed, but `set cmdheight=2` will be displayed.

I'll try to fix.

**Comment by liquidz** [comment]
@nbardiuk I tried to fix on `dev` branch.
Could you try `dev` branch?

**Comment by nbardiuk** [comment]
@liquidz I've just tried dev branch and it works! Thanks for the fix
