### ISSUE TITLE
Option for opening docs in vsplit

### ISSUE THREAD

**Issue by tami5** [liquidz/vim-iced#265]
Hi there, I'd like to open up docs created by <leader>hc in vsplit, I know that the size is adjustable via `g:iced#buffer#document#height`, but is there a way to make it open in a v-split or better decide based on frame size whether to open in v or h split.

Thanks

**Comment by liquidz** [comment]
Currently document buffer will be splited by `belowright` always.
https://github.com/liquidz/vim-iced/blob/2.2.0/autoload/iced/buffer/document.vim#L32

But it is possible to provide a modifier option  as well as stdout buffer.
https://github.com/liquidz/vim-iced/blob/2.2.0/autoload/iced/buffer/stdout.vim#L14

**Comment by liquidz** [comment]
@tami5 I tried to add a modifier option.
Could you try [feature/document_buffer_mod](https://github.com/liquidz/vim-iced/tree/feature/document_buffer_mod) branch with following setting?
```vim
let g:iced#buffer#document#mods = 'vertical'
```

**Comment by tami5** [comment]
Sure one moment

**Comment by tami5** [comment]
Nice works very well, Now is it possible to choose whether it opens left or right?

**Comment by tami5** [comment]
What is the buffer name? I'd like to add an autocmd to open folds.

Also, Thanks so much for quickly adding the feature

**Comment by liquidz** [comment]
Thanks for your confirmation!

> is it possible to choose whether it opens left or right?

You can choose it by vim side option.
https://vim-jp.org/vimdoc-en/options.html#'splitright'

> What is the buffer name? I'd like to add an autocmd to open folds.

Buffer name is `iced_document`.
https://github.com/liquidz/vim-iced/blob/2.2.0/autoload/iced/buffer/document.vim#L4

**Comment by tami5** [comment]
Oh I see, so its hard todo separately without changing built in option?

Thanks a lot. Will the changes be merged to dev or master soon?

**Comment by liquidz** [comment]
> its hard todo separately without changing built in option?

It maybe not hard to do, but it's low priority because we can do it in the vim's settings.

> Will the changes be merged to dev or master soon?

Merged to `dev` branch.

**Comment by tami5** [comment]
Thanks a lot, It is low priority and perhaps would be unnecessary.
