### ISSUE TITLE
Buffer with evaluations forms and their output

### ISSUE THREAD

**Issue by tami5** [liquidz/vim-iced#267]
Hi, Is there a way to get buffer with all evaluation history?

Thanks.

**Comment by liquidz** [comment]
Currently no.
What do you want to do in buffer with all evaluation history? Re-evaluation?

**Comment by tami5** [comment]
Its is extermlly helpful to see what is evaluated, to what value. Also, did the namespace file evaluate? is everything required? 

Some other features in mind:
- Syntax highlighting for both evaluation form and evaluation result.
- Foldable based on evaluation forms
- Indentation foldmethod for nested data tree
- toggle with a mapping

**Comment by liquidz** [comment]
You can use `IcedEvalAtMark` if you just want to re-evaluate.
https://liquidz.github.io/vim-iced/#evaluation_marks
But there's no history, so it may not be what you want.

It seems better to extend `Hook` to provide it as an external plugin.
https://liquidz.github.io/vim-iced/#hook

**Comment by tami5** [comment]
Hmmm, I'll try to play around with hooks and perhaps as part of learning process of scripting with vim, I can produce a plugin. Can you give somewhat compex hook that can be a starting point for me that involves vim-iced api?

Thanks

**Comment by liquidz** [comment]
Currently, hooks do not fire on evaluation.
So we should start to update hooks to fire on evaluation at first.

> Can you give somewhat compex hook that can be a starting point for me that involves vim-iced api?

Sorry, I'm using hooks only for notification for now, and I don't have complex examples.
