### ISSUE TITLE
<Plug>(iced_eval_and_replace) does not work with unnamed clipboard

### ISSUE THREAD

**Issue by nbardiuk** [liquidz/vim-iced#269]
Steps to reproduce:
 * `:set clipboard=unnamedplus`
 * yank some text
 * `<Plug>(iced_eval_and_replace)<Plug>(sexp_outer_list)`

Expected
 * form is replaced with the evaluation result

Actual
 * form is replaced with previously yanked text

More context:
 * it is neovim v0.4.4
 * evaluation result is available in register "0
 * `silent normal! gv"0p` works for me  https://github.com/liquidz/vim-iced/blob/2a11747137c3727b33e156bc2dcef9d29989e762/autoload/iced/operation.vim#L47

**Comment by liquidz** [comment]
@nbardiuk Thanks for your reporting!
I could reproduce the problem, and I also confirmed  evaluation result is yanked to `"0` register.

> silent normal! gv"0p works for me

Very helpful. Thanks!!

`gvp` seems to be used in addition to `<Plug>(iced_eval_and_replace)`, so I'll fix them.

**Comment by liquidz** [comment]
I released ver 2.3.1 since It was a wide area of influence.
Could you try latest version?

**Comment by nbardiuk** [comment]
It works, thank you for the fix! 🎉
