### ISSUE TITLE
Error while using `UseCaseOpen`

### ISSUE THREAD

**Issue by Fedreg** [liquidz/vim-iced#276]
Hello!

Just noticed an error while trying out the `UseCaseOpen` command:

<img width="1369" alt="image" src="https://user-images.githubusercontent.com/17401067/95781552-a8674c80-0c93-11eb-9ce3-076e19f1029e.png">

This happens either if I explicitly pass the symbol to the command or if I run while symbol is under cursor.

Running newovim 0.4.3 and here are my active plugins in case you spot anything in there.
Running latest iced-vim master (last updated on my end this weekend)
<img width="784" alt="image" src="https://user-images.githubusercontent.com/17401067/95781699-ff6d2180-0c93-11eb-9703-89b486efef51.png">

Let me know if I can provide any more info!  This isn't affecting me in any way; just wanted to flag for you.  thx!!

**Comment by liquidz** [comment]
@Fedreg Thanks for your reporting!

`UseCaseOpen` has some synchronous processing and seems to be timed out there.
I'll change to asynchronous processing and also allow to use clj-kondo's static analysis data.

**Comment by Fedreg** [comment]
@liquidz Ya, it was on a pretty large codebase so that could definitely be it.  thx!!

**Comment by liquidz** [comment]
@Fedreg Sorry for the delay.
I tried to fix the problem in `dev` branch.
Could you try `dev` branch?

**Comment by Fedreg** [comment]
@liquidz  No prob!!!!

Yup, pulled in Dev and it works great!!!  Timeout is gone.  
Thank you for fixing so quickly!!

**Comment by liquidz** [comment]
@Fedreg Thanks for your confirmation!

**Comment by liquidz** [comment]
Closed by #278
