### ISSUE TITLE
Jet asks to install every time

### ISSUE THREAD

**Issue by Futurile** [liquidz/vim-iced#284]
Each vim-iced session when I use the `IcedSourceShow` command it asks me if I want to install `jet`. I already have `jet` installed. If I say 'no' to the dialog then it will show the source. All subsequent calls to `IcedShowSource` show the source without asking me to install `jet`.

I would expect vim-iced to check if jet has already been installed and to only prompt to install it if it is not available.

It looks like you check in edn.vim and do set it to to be v:true after decoding happens. But, I couldn't figure out the path (and have very limited/no viml knowledge).

Changing the edn.is_available function to check does fix it, but I'm not sure if this is the correct place. For `bb` in script.vim there seems to be a specific set-up function which might be more correct logic:

```
function! s:edn.is_available() abort
    if executable('jet')
        let s:edn.available = v:true
    endif
  return self.available
endfunction
```

**Comment by liquidz** [comment]
@Futurile Thanks for your reporting!

> Each vim-iced session when I use the IcedSourceShow command it asks me if I want to install jet. I already have jet installed.

It's weird.
As you know, vim-iced will check the existence of jet for the first time of use.
https://github.com/liquidz/vim-iced/blob/2.4.0/autoload/iced/component/edn.vim#L39-L52

What is ouput as a result of executing `:echo executable('jet')` command?
If `0`, could you confirm that your `PATH` environmental variable contains the path for the `jet`?
c.f. https://vim-jp.org/vimdoc-en/eval.html#executable()

BTW: It's not a radical solution, but you can also disable `g:iced_enable_enhanced_definition_extraction` option.
https://liquidz.github.io/vim-iced/#_enhanced_source_extraction
```
let g:iced_enable_enhanced_definition_extraction = v:false
```

**Comment by Futurile** [comment]
This was my error, I didn't have the location in my PATH where it was installing iced/jet etc.
