### ISSUE TITLE
No reader function for tag feature 

### ISSUE THREAD

**Issue by tami5** [liquidz/vim-iced#287]
Hey @liquidz 

I'm getting error message No reader function for tag feature  after connecting to the repl

**Comment by liquidz** [comment]
@tami5 Thanks for your reporting!

Could you tell me minimal steps to reproduce?

**Comment by tami5** [comment]
Here you ho

nvim -Nu test.vim

```
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'junegunn/fzf', { 'do': './install --bin' }
Plug 'junegunn/fzf.vim'
Plug 'guns/vim-sexp',    {'for': 'clojure'}
Plug 'liquidz/vim-iced', {'for': 'clojure'}
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync

```

**Comment by tami5** [comment]
I'm using nvim nightly btw

**Comment by liquidz** [comment]
Hmm.. I could not reproduce the problem.

```
$ lein new foo
$ cd foo
$ nvim src/foo/core.clj
```

Then I did `:IcedConnect` and `:IcedEvalOuterTopList` commands, and got no errors.

I confirmed above steps with NVIM v0.5.0-812-gd17e50879.

**Comment by tami5** [comment]
Hmm so this maybe on lein level project level?

Let me recheck and reopen if the issue continue. Thanks a lot @liquidz

**Comment by liquidz** [comment]
I think it maybe project level.
Is there an `#foo`-like description left somewhere in your code?
