### ISSUE TITLE
iced_stdout_buffer_toggle

### ISSUE THREAD

**Issue by tami5** [liquidz/vim-iced#291]
Hey @liquidz I think there should `iced_stdout_buffer_toggle` instead of close/open this way it would be one mapping for the user.

Also it would be cool if we can have a veration for opening the stdout buffer. like <leader>ss horizontal split, <leader>sv vertical split ..

Thanks

**Comment by liquidz** [comment]
@tami5 Thanks for your suggestion!

`iced_stdout_buffer_toggle` is a good idea.

> Also it would be cool if we can have a veration for opening the stdout buffer. like ss horizontal split, sv vertical split ..

Currently `ss` depends on [g:iced#buffer#stdout#mods](https://liquidz.github.io/vim-iced/vim-iced.html#g%3Aiced%23buffer%23stdout%23mods).

**Comment by liquidz** [comment]
I just added the `IcedStdoutBufferToggle` command to try it out.

**Comment by tami5** [comment]
Oh nice, thanks a lot @liquidz . For the  g:iced#buffer#stdout#mods I think I can get away with creating a mapping that will set the value of the g:iced#buffer#stdout#mods then run IcedStdoutBufferToggle for now.

Thanks a lot :heart:

**Comment by liquidz** [comment]
Thanks for your confirmation!
I'll merge and release in this weekend.

**Comment by liquidz** [comment]
@tami5 FYI, I just cut a new release #293

**Comment by tami5** [comment]
Nice thanks @liquidz , I'm looking into make help docs and stdout floating window in neovim. I'm going to share simple implementation if I succeeded

**Comment by tami5** [comment]
Also, I think toggling should be applied to document as well.

**Comment by liquidz** [comment]
> Also, I think toggling should be applied to document as well.

Do you mean toggling for IcedDocumentOpen?
https://liquidz.github.io/vim-iced/vim-iced.html#%3AIcedDocumentOpen

**Comment by tami5** [comment]
Yep

**Comment by liquidz** [comment]
In IcedDocumentOpen, the content to be displayed differs depending on the symbol under the cursor, so when toggling, we need to consider when and what to display and when to close.

(E.g. if the symbol under the cursor is the same as the one currently displayed, close it, and if it is different, change the displayed content)

**Comment by tami5** [comment]
Oh makes sense

**Comment by tami5** [comment]
Also @liquidz https://camo.githubusercontent.com/27a104fdd1d4a52bedaa79bff3afbac6f8b0137339179b374828022060396e76/68747470733a2f2f61736369696e656d612e6f72672f612f3332353531372e737667 any plans to support such experience. Its could replace stdout. both the buffer and side popup is really useful. Please consider it

**Comment by liquidz** [comment]
Currently I have no plan to support such feature, but now that I've recognized your request, so I'll consider what is the best way to do it.

**Comment by tami5** [comment]
:heart:
