### ISSUE TITLE
Indentation takes a while to execute

### ISSUE THREAD

**Issue by tami5** [liquidz/vim-iced#294]
Hey @liquidz , I don't know why iced does this but is there a way to disabling indentation by vim-iced. By the way this didn't happen for me before.

Thanks

**Comment by liquidz** [comment]
See this comment
https://github.com/liquidz/vim-iced/issues/263#issuecomment-694510943

BTW I didn't change any operation about indenting in recent releases

**Comment by tami5** [comment]
Awesome thanks
