### ISSUE TITLE
Autoconnecting issue

### ISSUE THREAD

**Issue by tami5** [liquidz/vim-iced#301]
Hey @liquidz 

Somehow I did something that might of resulted in a bug. To reporduce:

- iced repl
- IcedConnect
- Eval -main
- run -main
- runs okay, finishes, then here the issue I get autoconnecting message
- Any trials to connect again or eval again fail.

```clj
(ns app.core
  (:refer-clojure :exclude [map reduce into partition partition-by take merge transduce])
  (:require [clojure.core.async :refer :all :as async]))

(defn -main
  [& args]
  (println "Starting ..")
  (let [my-q (chan 5)
        my-seq (seq "Hello World")]  
    (a/go ;; Put stuff into the queue
      (doseq [item my-seq]
        (>! my-q item)
        (<! (timeout 1000))))
    (go
      (while true
        (let [c (<! my-q)]
          (println c))))
    (future (Thread/sleep 12000) (println "-"))
    (shutdown-agents)
    (println "Finished!")))

(-main)
```  

Thanks

**Comment by liquidz** [comment]
@tami5 `(shutdown-agents)` should be the cause.
https://clojuredocs.org/clojure.core/shutdown-agents

`shutdown-agents` will affect `future`, `pmap`, etc.., and it also leads to shutdown nREPL server as follows.

```sh
# start nREPL server
$ lein repl :start :port 50000

# connect nREPL server by other terminals.
$ lein repl :connect 50000
user=> (shutdown-agents)
nil
user=>
SocketException The transport's socket appears to have lost its connection to the nREPL server
```

So you should not evaluate `(shutdown-agents)` on nREPL.

**Comment by tami5** [comment]
😝 That was so dumb on my part. Thanks for clarifying.
