### ISSUE TITLE
Wrap option for document popup

### ISSUE THREAD

**Issue by nbardiuk** [liquidz/vim-iced#309]
Documentation for java symbols is long string without line breaks which get cut at the right endge of the popup.

![1611265110](https://user-images.githubusercontent.com/381992/105415870-39ee3f00-5c31-11eb-9e29-d7909af998a5.png)

As I understand cider/orchard [parses javadoc](https://github.com/clojure-emacs/orchard/blob/master/src/orchard/java/parser.clj#L144) from html content. Unfortunately html does not preserve original line breaks and they get lost.

Could it be possible to add an option to enable `wrap` for document popup?
Or maybe a maxwidth option like `textwidth` that would reformat content of popup with hard wrap.

**Comment by liquidz** [comment]
@nbardiuk Thanks for your reporting!

It seems `maxwidth` is not calculated correctly. I'll fix it.
https://github.com/liquidz/vim-iced/blob/2.7.4/autoload/iced/component/popup/vim.vim#L91

**Comment by nbardiuk** [comment]
Great! Forgot to mention that I am using neovim 0.4.4

**Comment by liquidz** [comment]
@nbardiuk I tried to fix in `dev` branch.

**Comment by nbardiuk** [comment]
@liquidz I've tried the dev branch. It fixed the issue for me. Thank you 👍🏻

**Comment by liquidz** [comment]
Thanks for your confirmation!
I just cut a new release.
