### ISSUE TITLE
Code formatting doesn't work with babashka nrepl

### ISSUE THREAD

**Issue by hamann** [liquidz/vim-iced#313]
With default code formatting settings being connected to babashka nrepl just does nothing. As a workaround I constantly update vimrc to set `joker` when being in bb environment and change it again otherwise.

**Comment by liquidz** [comment]
@hamann Default formatter does not support babashka nrepl for now.
Default formatter uses iced-nrepl which is a nrepl middleware and babashka nrepl does not support to use custom nrepl middleware.
https://github.com/liquidz/iced-nrepl

So you should use custom formatter. (I'm using cljstyle for all my/work projects)

**Comment by hamann** [comment]
Ok, thanks for the answer. I'll have a look at cljstyle
