### ISSUE TITLE
Option to choose selector

### ISSUE THREAD

**Issue by Deraen** [liquidz/vim-iced#318]
Hi,

I have both FZF and Vim-clap installed and I'd prefer to use Clap for selector in Vim-iced.

Looking at autoload/iced/component/selector.vim there doesn't seem to be option to choose the selector currently.

**Comment by liquidz** [comment]
@Deraen Indeed! I'll add the option.

**Comment by liquidz** [comment]
@Deraen Just released v3.0.1
Please refer the following section
https://liquidz.github.io/vim-iced/vim-iced.html#g%3Aiced%23selector%23search_order

**Comment by Deraen** [comment]
Thanks, I can confirm this works.

**Comment by liquidz** [comment]
Thanks for your confirmation!
