### ISSUE TITLE
Command to evaluate entire buffer?

### ISSUE THREAD

**Issue by mizlan** [liquidz/vim-iced#322]
Is there a command to evaluate the entire buffer? Something like `C-c C-k` in Emacs if that helps.

**Comment by liquidz** [comment]
@mizlan `<Leader>eb` will evaluate the current buffer
https://liquidz.github.io/vim-iced/vim-iced.html#%3AIcedRequire
https://liquidz.github.io/vim-iced/#cheatsheet

**Comment by mizlan** [comment]
Ah, I was confused by the word "require." Thanks for the lightning-fast response!
