### ISSUE TITLE
Possible to use this without a project?

### ISSUE THREAD

**Issue by mizlan** [liquidz/vim-iced#325]
Is it possible to use vim-iced functionality without a project? I am editing some single-file Clojure files as scripts and don't want to build full project structure for it. I understand that some of the functionality may be limited, but is there anything that can be used? I cannot start a `iced repl` since there is no project.

**Comment by nbardiuk** [comment]
As workaround, you can create a deps.edn file without dependencies as a simple "project"

```
echo '{}' > deps.edn
iced repl
```

**Comment by liquidz** [comment]
@mizlan You can use [:IcedInstantConnect](https://liquidz.github.io/vim-iced/vim-iced.html#%3AIcedInstantConnect)

**Comment by mizlan** [comment]
Thank you.
