### ISSUE TITLE
Installation fails without specifying branch

### ISSUE THREAD

**Issue by NoahTheDuke** [liquidz/vim-iced#335]
Hey all! I just realized I haven't been using the latest version because of the switch from "master" branch to "main", so I deleted `~/.vim/plugged/vim-iced` and then opened vim and ran `:PlugInstall` and got this error:

```
Updated. Elapsed time: 3.365896 sec.
- Finishing ... Done!
x vim-iced:
    fatal: invalid reference: master
```

If I change the Plug invocation to `Plug 'liquidz/vim-iced', {'for': 'clojure', 'branch': 'main'}`, `:PlugInstall` works again.

Should this be mentioned in the installation instructions or should I reach out to the vim-plug folks?

**Comment by liquidz** [comment]
@NoahTheDuke Thanks for your reporting!

In my environment, I couldn't reproduce the problem.

Are you sure that your vim-plug is latest?
https://github.com/junegunn/vim-plug/pull/1007

**Comment by NoahTheDuke** [comment]
You are correct, that was the issue! Thanks for pointing me in the right direction.
