### ISSUE TITLE
Having trouble connecting to shadow-cljs nrepl

### ISSUE THREAD

**Issue by noahmoss** [liquidz/vim-iced#347]
Hi @liquidz!

I'm trying to setup vim-iced to work on some clojurescript in https://github.com/metabase/metabase, using shadow-cljs. I'm having trouble getting it to work since my knowledge of this area is currently very surface-level.

When I follow [the instructions in the docs](https://liquidz.github.io/vim-iced/#clojurescript_shadow_cljs), `iced repl app` (where `app` is my build id) gives me an error saying `'app' is not a task`. And I don't see `IcedEvalRepl` as a command included in the plugin.

I'm also getting these errors when I run `iced repl` in the repo without making any edits to the dependencies. I mentioned this in #344 but I still don't quite understand the cause.
```
Error loading cider.piggieback: Syntax error macroexpanding clojure.core/ns at (cljs/source_map/base64_vlq.clj:1:1).
...
Syntax error compiling var at (/private/var/folders/jn/ysbp4fbd64v3z0vnn0w9gpbw0000gn/T/form-init3474645777214805796.clj:1:7772).
Unable to resolve var: cider.piggieback/wrap-cljs-repl in this context
```

Here's the closest I've gotten to getting it working:
* I remove `cider.piggieback/wrap-cljs-repl` from `shadow-cljs.edn`
* I add imports of `org.clojure/clojurescript` and `thheller/shadow-cljs` into project.clj
* I run `iced repl`, and it starts without errors
* I run `shadow-cljs watch app`, it starts but prints out a bunch of errors like `FileNotFoundException Could not locate cider/nrepl__init.class, cider/nrepl.clj or cider/nrepl.cljc on classpath.`
* I open a cljs file, run `IcedConnect` and select `nrepl`
* I run `:IcedStartCljsRepl shadow-cljs app`. It prints out `Unable to find static field: ECMASCRIPT6_TYPED in class com.google.javascript.jscomp.CompilerOptions$LanguageMode`. When I try to evaluate anything, I see `Session error. You should be in cljs session.`

This was all trial and error so I'm really not sure if I'm on the right track at all. Any advice would be greatly appreciated! :)

**Comment by liquidz** [comment]
@noahmoss Thanks for your reporting!

The `iced repl` command will automatically search project files (such as project.clj and shadow-cljs.edn) and launch the appropriate REPL for the project.

When multiple projects are found, `iced repl` command prefer project.clj.
So it seems to fail starting the shadow-cljs's nREPL.

Could you try the following command?
```
iced repl --force-shadow-cljs app
```

There is a lack of documentation on this, so I will update it.

**Comment by liquidz** [comment]
@noahmoss oh, thank you so much for your sponsoring!!

**Comment by noahmoss** [comment]
@liquidz I ran `iced repl --force-shadow-cljs app` and it prompted me to create `.nrepl.edn`, then started up the nREPL successfully.

Then, I opened a cljs file. After a moment it printed `CLJS repl has started.` But then when I try to evaluate a form, this is printed to stdout:
```
No available JS runtime.
See https://shadow-cljs.github.io/docs/UsersGuide.html#repl-troubleshooting
```

**Comment by liquidz** [comment]
@noahmoss Did you access your local metabase from browser before you connecting repl?

https://liquidz.github.io/vim-iced/#clojurescript_shadow_cljs
> Access shadow-cljs’s HTTP server in your browser

**Comment by noahmoss** [comment]
@liquidz I'm a bit confused about this. We're currently not using shadow-cljs for the full frontend, just for a small amount of shared code. Here's the full output of `iced repl --force-shadow-cljs app` with nothing else running:

```
OK: CLJS option is enabled.
OK: shadow-cljs project is detected
OK: For shadow-cljs project, start watching instead of starting REPL.
shadow-cljs - config: /Users/noahmoss/metabase/shadow-cljs.edn
shadow-cljs - updating dependencies
shadow-cljs - dependencies updated
shadow-cljs - server version: 2.11.20 running at http://localhost:9630
shadow-cljs - nREPL server started on port 59881
shadow-cljs - watching build :app
[:app] Configuring build.
[:app] Compiling ...
[:app] Build completed. (150 files, 0 compiled, 0 warnings, 7.85s)
```

I see in the [shadow-cljs docs](https://shadow-cljs.github.io/docs/UsersGuide.html#nREPL) that it normally also starts an HTTP server, but that doesn't seem to be happening here. Is it still possible to connect it with vim-iced without this?

**Comment by liquidz** [comment]
@noahmoss ah sorry, I overlooked build target.
To be available JS runtime, you need to inspect as follows instead of accessing from browser.
https://github.com/liquidz/merr/blob/main/Makefile#L16

**Comment by noahmoss** [comment]
@liquidz What path do I provide for `node --target`?

As far as I can tell, cljs code is compiled to a large number of different files in `metabase/frontend/src/cljs`. There's no `target/js/compiled/index.js`.

**Comment by liquidz** [comment]
Hmm, I'll have a look

**Comment by liquidz** [comment]
It seems a matter of shadow-cljs when targets `node-module`.

https://webcache.googleusercontent.com/search?q=cache:fatymZ-azcEJ:https://clojurians-log.clojureverse.org/shadow-cljs/2020-08-25+&cd=1&hl=ja&ct=clnk&gl=jp

thheller says:
> you mean the repl troubleshoot section doesn't specifically mention :npm-module? thats because there are a bazillion gazillion ways to use :npm-module and I can't possibly list all the "solutions"

**Comment by liquidz** [comment]
Hmm... I have no idea...

@noahmoss It may be good to ask how to enable JS runtime with `npm-module` at `#shadow-cljs` channel in clojurians slack.

**Comment by noahmoss** [comment]
Interesting, thanks for your help. I'll try to chase this thread and see if I can get anywhere.

**Comment by noahmoss** [comment]
I didn't totally figure this out (don't actually need to edit cljs files right now) but I'll close this issue since I think the rest is related to `shadow-cljs` rather than `vim-iced`.
