### ISSUE TITLE
Trouble with connecting to shadow-clj repl via clojure cli. 

### ISSUE THREAD

**Issue by smnplk** [liquidz/vim-iced#350]
I am sorry I have to ask this here, but I don't think anyone could answer this one on StackOwerflow, because it's a niche project. 

My version of iced is  3.5.2

So my setup is the following. I am using a  clojure cli tool, so I have a deps.edn project file

```clojure
{:deps {}
 :paths ["src/main" "src/test" "resources" "dev"]
 :aliases { :test {:extra-paths ["test"]}
                :shadow-cljs {:extra-deps {thheller/shadow-cljs {:mvn/version "2.14.5"}
                                                          reagent/reagent      {:mvn/version "1.0.0-rc1"}
                                                          re-frame/re-frame    {:mvn/version "1.1.2"}}
                                      :main-opts ["-m" "shadow.cljs.devtools.cli"]}}}
```

Although I am using shadow-cljs compiler from the clojure cli tool. So I can run a shadow-cljs watcher like this:

**clj -M:shadow-cljs watch app** 

But I want to connect to shadow-cljs clojurescript repl via iced-vim. 

The steps I do: 

**1.) iced repl --with-cljs** 
OK: CLJS option is enabled.
OK: Clojure CLI project is detected
...
**2.) In nvim I connect with :IcedConnect** 
Connected.
All is fine up to here. I can eval clj code. 

**3.)I try to start clojurescript repl in nvim via 
    :IcedStartCljsRepl shadow-cljs app**

but on step 3 I get the following error: 
`Could not locate shadow/cljs/devtools/api__init.class, shadow/cljs/devtools/api.clj or shadow/cljs/devtools/api.cljc on classpath.`

I am newb with vim-iced, so there must be something simple i am missing here. And I have to mention that I already had this working a few days ago, I just forgot what the steps were to connect to shadow-cljs repl. It looks like the main clj repl that is ran via clojure cli doesn't add shadow-cljs lib to the classpath. 

Then i tried to run the repl like this: 
**iced repl --with-cljs --force-clojure-cli --dependency=thheller/shadow-cljs:2.14.5**

then after doing step 3 , i get the following error: 

```
Execution error (ExceptionInfo) at shadow.cljs.devtools.server.runtime/get-instance! (runtime.clj:11).
shadow-cljs has not been started yet!
In embedded mode you need to call (shadow.cljs.devtools.server/start!) to start it.
If you have a shadow-cljs server or watch running then you are not connected to that process.
```

**Comment by liquidz** [comment]
@smnplk
> clj -M:shadow-cljs watch app

You should have shadow-cljs.edn for `app` configuration.
So the easiest way is to start a REPL from shadow-cljs.edn like follows.

* shadow-cljs.edn
```clj
{:deps {:aliases [:shadow-cljs]} ;; use :shadow-cljs alias in deps.edn
 ... }
```
* deps.edn
```clj
{:deps {}
 :paths ["src/main" "src/test" "resources" "dev"]
 :aliases {:test {:extra-paths ["test"]}
           :shadow-cljs {:extra-deps {thheller/shadow-cljs {:mvn/version "2.14.5"}
                                      reagent/reagent      {:mvn/version "1.0.0-rc1"}
                                      re-frame/re-frame    {:mvn/version "1.1.2"}}}}}
                         ;; :main-opts is not required when starting REPL from shadow-cljs
                         ;; :main-opts ["-m" "shadow.cljs.devtools.cli"]}}}
```
* Start REPL
```
$ iced repl --force-shadow-cljs app
```
* Open your local server to enable JS runtime
  * c.f. https://github.com/thheller/shadow-cljs#quick-start
* Open your source file and execute `:IcedConnect`
  * CLJS repl should start automatically. You don't need to execute `:IcedStartCljsRepl ...`

FYI, `iced` command injects some additional dependencies and nREPL middlewares (such as cider-nrepl and iced-nrepl) when starting REPL.
Starting REPL from `clj` directly will not inject them, and correct behaviros cannot be expected.

**Comment by smnplk** [comment]
> FYI, iced command injects some additional dependencies and nREPL middlewares (such as cider-nrepl and iced-nrepl) when starting REPL.
Starting REPL from clj directly will not inject them, and correct behaviros cannot be expected.

I was aware of that.  I didn't try to connect to REPL ran with that command.

> You should have shadow-cljs.edn for app configuration.
   So the easiest way is to start a REPL from shadow-cljs.edn like follows.

I have it.  But the alias part in shadow-cljs.edn (referencing my :shadow-cljs alias in deps.edn) was missing.
In my shadow-cljs.edn i had **:deps true**, now i changed it to **:deps {:aliases [:shadow-cljs]}**

I also had to install shadow-cljs npm packet in local dir **npm install shadow-cljs --save-dev**, which I didn't have to do before.

All is good now, it works. I am automatically connected to Clojurescript REPL when I am editing a .cljs file. When I switch to .clj file, I just have to run the :IcedCycleSession command. I hope this is as intended. 

@liquidz  Thanks for this cool project, I can finally switch from Emacs to Nvim.

**Comment by liquidz** [comment]
@smnplk Good to hear that!

> When I switch to .clj file, I just have to run the :IcedCycleSession command. I hope this is as intended.

You can use `g:iced#nrepl#auto#does_switch_session` option to switch sessions automatically.
https://liquidz.github.io/vim-iced/vim-iced.html#g%3Aiced%23nrepl%23auto%23does_switch_session
