### ISSUE TITLE
Error when clearing stdout buffer in neovim

### ISSUE THREAD

**Issue by noahmoss** [liquidz/vim-iced#351]
If I open the stdout buffer, print some data to it, and then press `<leader>sl` to clear the buffer, I see the following error.

```
Error detected while processing function iced#buffer#stdout#clear[1]..iced#buffer#clear[2]..iced#compat#deletebufline:
line   14:
E5555: API call: Vim:Error executing lua callback: [string "<VimL compiled string>"]:1: Vim(call):E16: Invalid range:  call s:RemoveRange(start, end) | endif
```

Pressing enter does clear the buffer, so it's not a huge deal, but a bit annoying that this pops up every time.

I'm on nvim 0.4.4

**Comment by liquidz** [comment]
@noahmoss Thanks for your reporting!

Hmm, I've never seen such error in my daily usages.
With [minimal configuration](https://liquidz.github.io/vim-iced/#minimal_configuration), I cannot reproduce the problem.

But I can confirm the problem with [your dotfiles](https://github.com/noahmoss/dotfiles), so I'll try to examine it in detail.

**Comment by noahmoss** [comment]
@liquidz Thank you! If it's a problem with my dotfiles I'll try to dig into it myself later today. :)

**Comment by liquidz** [comment]
@noahmoss As far as I've tried, commenting out the following plugin will fix the problem.
https://github.com/noahmoss/dotfiles/blob/8fb5fab3aa4c531571c9267a72642c952556a398/.vim/vimrc#L191

This plugin affects any buffers, so It may be a problem.
https://github.com/axelf4/vim-strip-trailing-whitespace/blob/9a93dd653806ba3f886b2cf92111b663ce8d44bd/plugin/strip_trailing_whitespace.vim#L235-L239

**Comment by noahmoss** [comment]
Brilliant, looks like that plugin was the issue, thank you!
