### ISSUE TITLE
Custom test form names for State Flow

### ISSUE THREAD

**Issue by guilhermedallanol** [liquidz/vim-iced#364]
Hey everyone, me again.

The company that I'm currently working developed its own testing framework called [state-flow](https://github.com/nubank/state-flow). When I try to run one of those tests, I get this error:
```
 Unable to resolve symbol: defflow in this context
```
After asking around, they told me that for `conjure`, they solve this problem with this:

`let g:conjure#client#clojure#nrepl#test#current_form_names = ['deftest', 'defflow']`

I couldn't find anything related to this in the docs. Any ideas on how to solve that?

Thank you!

**Comment by liquidz** [comment]
@guilhermedallanol In my environment, state-flow works.

```clj
(ns foo.core-test
  (:require
    [state-flow.api :refer [defflow match?]]))

;; run :IcedTestUnderCursor in the next form
(defflow test-flow
  (match? 1 1))

(meta #'test-flow) ;; => {:test #function[foo.core-test/fn--16175], ....}
```

vim-iced uses metadata to check the current form is test or not.
And `defflow` defines a var with `:test` metadata as same as `clojure.test/deftest`, so vim-iced can handle vars with `defflow` as test vars.

BTW, I found a bug in the handling of errors in the state-flow test, so I'll fix it.

**Comment by liquidz** [comment]
> BTW, I found a bug in the handling of errors in the state-flow test, so I'll fix it.

More specifically, it was a bug about handling test results which does not contain file path information.
I've fixed it in dev branch for now.
https://github.com/liquidz/vim-iced/tree/dev

**Comment by guilhermedallanol** [comment]
@liquidz I just noticed what I was doing wrong. The `:require` was only allowing `flow` insteade of `defflow`. When I added `defflow` it worked as expected.

Thank you again!
