### ISSUE TITLE
Add split size customization option to stdout buffer

### ISSUE THREAD

**Issue by noomly** [liquidz/vim-iced#366]
First of all, thank you for the work you're doing with vim-iced, it's a neat tool and it fits almost perfectly in my workflow out of the box.

I have been reading the `vim-iced-customizing-stdout-buffer` section of the help page in an attempt to configure the way the stdout buffer is splitted. It seems that while it is possible to customize the position/direction of the new split, it's not possible to configure its size. So I always find myself jumping to that split, resize it (in height for my case) and come back to my code split.

It would be very useful in my case to be able to configure the stdout size to, for examples: a number of lines/columns, or a percentage of the window's total lines/columns.

Is this a feature that could be easily implemented in vim-iced?

**Comment by liquidz** [comment]
@noomly Thanks for your suggestion!

> Is this a feature that could be easily implemented in vim-iced?

Yeah, it's easy and the feature seems good to me too.
I just cut a new release(#367) and added the following option :) 
https://liquidz.github.io/vim-iced/vim-iced.html#g%3Aiced%23buffer%23stdout%23size

Could you try the latest version?

**Comment by noomly** [comment]
I just tried and it works perfectly for my use case, thank you for your reactivity!

I'm closing this issue. I just had another unrelated question, is there any reason why this split is designed to only display stdout? What about stderr? Should I open another issue about this?

**Comment by liquidz** [comment]
@noomly Thanks for your confirmation!

> I just had another unrelated question, is there any reason why this split is designed to only display stdout? What about stderr? Should I open another issue about this?

Ah sorry, it's a naming problem.
stdout buffer also displays stderr outputs.

```clj
(.println *err* "this message will be displayed in stdout buffer")
```
