### ISSUE TITLE
Popup window gets stuck when using babashka 

### ISSUE THREAD

**Issue by b-ryan** [liquidz/vim-iced#370]
Hey there,

I'm trying to use vim-iced with babashka and the popup window gets stuck. For example, upon initial connection the stdout popup hangs around

![image](https://user-images.githubusercontent.com/1183997/141162240-5ad60df9-5ac4-42f6-a9da-5580b3709d76.png)

If I then open up docs with K, the stdout popup disappears and now the docstring popup stays there.

**Comment by b-ryan** [comment]
Same behavior when using socket repl and nrepl.

**Comment by liquidz** [comment]
@b-ryan Thanks for your report!
Hmm, I couldn't reproduce the problem with vim 8.2.3458 and nvim 0.6.0-dev+1483-g75f758b99.

Could you tell me
* Which version of vim/nvim are you using?
* Can you reproduce the problem with the minimal configuration?
  * https://liquidz.github.io/vim-iced/#minimal_configuration

**Comment by Cnly** [comment]
I'm using a Clojure CLI repl and the floating window can get stuck if I press `K` in the stdout buffer. It won't go away until I switch to another window. File buffers seem to be fine: they close as soon as I press `j` or `k`.

This is on `NVIM v0.5.1` and it's reproducible with the minimal config.

**Comment by liquidz** [comment]
@Cnly Thanks for your reporting!

I'll have a look this weekend.

**Comment by liquidz** [comment]
@Cnly I could reproduced the problem and fixed.
Could you try [dev](https://github.com/liquidz/vim-iced/tree/dev) branch?

**Comment by Cnly** [comment]
@liquidz I can confirm it's fixed. Thank you!

**Comment by liquidz** [comment]
@Cnly Thanks for your confirmation! Just released v3.7.1 #373

**Comment by b-ryan** [comment]
Sorry for the poor bug report and radio silence. I finally got around to trying to find out more info here. My version of nvim is v0.4.3 

I discovered this behavior only happens when I am editing a file that doesn't have the `.clj` file extension, for example if you make a file named `test-it` with these contents:

```clojure
#!/usr/bin/env bb
;; vim: ft=clojure

(inc 3)
```

For now I can rename my file to get around the issue.

**Comment by liquidz** [comment]
@b-ryan Thanks!
Ah, this is the cause.
https://github.com/liquidz/vim-iced/blob/d65495122c95b8c1bf447c6c5d2c00e745269e5e/ftplugin/clojure.vim#L343-L351

Hmm, I'll find the way to work with it.

**Comment by liquidz** [comment]
@b-ryan Fixed.
Could you try [dev](https://github.com/liquidz/vim-iced/tree/dev) branch?

**Comment by b-ryan** [comment]
Yep, it's fixed on the dev branch.

**Comment by liquidz** [comment]
@b-ryan Thanks for your confirmation!
I just released v3.7.5 #381
