### ISSUE TITLE
Bump refactor-nrepl

### ISSUE THREAD

**Issue by vemv** [liquidz/vim-iced#374]
Hi there!

the 3.X series of refactor-nrepl contains a lot of improvements and no breaking changes.

You might appreciate upgrading it.

https://metaredux.com/posts/2021/10/26/clj-refactor-3-0.html

https://github.com/clojure-emacs/refactor-nrepl/blob/master/CHANGELOG.md

Cheers - V

**Comment by liquidz** [comment]
@vemv Thanks!
I have a plan to update it after currently fixing issues are over.

**Comment by liquidz** [comment]
Just released v3.7.3 #377

**Comment by vemv** [comment]
Cheers, hope it keeps being of use!
