### ISSUE TITLE
Change color of temporary evaluation result?

### ISSUE THREAD

**Issue by mars0i** [liquidz/vim-iced#389]
When evaluating code with `<Leader>ei`, `<Leader>et`, etc., the result is temporarily displayed to the right of the line after "=> ".  The displayed result is in the the `Comment` color from the user's color scheme.  

Is there a way to change this color to make it different from the `Comment` color?  Since comments are static parts of a source file, and the evaluation result is temporary, for me it would be nicer if the color of the evaluation result conveyed that it was temporary and made it stand out.  (I know I can change the color of the temporary result display by changing my `Comment` color, but I want the result display to be in a different color from my comments.)

Or if there's no way to change it, maybe I could just modify my own copy of the .vim viles to make the color different?  I haven't yet figured out which file this is in.    Thanks.

**Comment by liquidz** [comment]
@mars0i Thanks for your reporting!
Currently, the highlight setting for popuped results are fixed.

You can change it at below:
https://github.com/liquidz/vim-iced/blob/a28cd81990d46816b599f10cafe69ea7e4898f9f/autoload/iced/nrepl/eval.vim#L57

But it may be good to add option for modifing the highlight setting.

**Comment by mars0i** [comment]
Thanks @liquidz!  I've changed it now.

I like the idea of adding an option for changing the highlight setting for the evaluation results.  I suppose that some people might want to be able to configure other colors, such as the stdout popup.  (I don't need to change the stdout popup colors.)

**Comment by liquidz** [comment]
@mars0i I added `g:iced#eval#popup_highlight` option to change the highlight setting to `dev` branch.
https://vim-iced-nightly.netlify.app/vim-iced.html#g%3Aiced%23eval%23popup_highlight

Could you try [dev](https://github.com/liquidz/vim-iced/tree/dev) branch?

**Comment by mars0i** [comment]
Yes, works perfectly for me.  Thank you!

**Comment by liquidz** [comment]
@mars0i Just released v3.8.3 #392

**Comment by mars0i** [comment]
Excellent--thanks.  I just updated.
