### ISSUE TITLE
Custom messages in tests with `is` aren't shown

### ISSUE THREAD

**Issue by geekingfrog** [liquidz/vim-iced#408]
Let's consider the following test:

```clojure
(deftest test-with-message
  (testing "will fail"
    (is false "what did you expect?")))
```
Running `lein test` will give the following:
```
FAIL in (test-with-message) (core_test.clj:21)
will fail
what did you expect?
expected: false
  actual: false
```

But running the test using iced doesn't give me the `what did you expect?` string:
```
;; test-with-message: will fail (Line: 21)
expected: false
  actual: false
```

Otherwise things just work, fantastic work <3

**Comment by liquidz** [comment]
@geekingfrog Nice catch! Thanks for your reporting!
I've fixed in [dev](https://github.com/liquidz/vim-iced/tree/dev) branch, and it should be displayed as below.
```
;; test-with-message: will fail / what did you expect? (Line: 7)
expected: false
  actual: false
```
Could you try dev branch?

**Comment by geekingfrog** [comment]
Works on `dev`, thanks for the quick fix.

**Comment by liquidz** [comment]
@geekingfrog Just release v3.9.0 #409
