### ISSUE TITLE
Customizing the configuration of the internal formatter

### ISSUE THREAD

**Issue by ixffxi** [liquidz/vim-iced#411]
As the vim-iced documentation says, the following is already possible:

```
let g:iced#format#rule = {
      \ 'merr.core/let': '[[:block 2] [:inner 1]]',
      \ }
```

It would be great, if you could pass in the top configuration map for cljfmt here instead and by doing so change settings like:

```
{:remove-surrounding-whitespace? true
 :remove-trailing-whitespace? true
 :remove-consecutive-blank-lines? false
 :insert-missing-whitespace? true
 :remove-multiple-non-indenting-spaces? false
 ...
}
```

Thank you for making vim-iced 💯 
🙇

**Comment by liquidz** [comment]
@ixffxi Thanks for your confirmation!

> One small find in the new section of the documentation: "Default valud (<-- typo) is {}."

Oh, nice catch! I've fixed, and just released v3.9.1 #415 ☺️
