### ISSUE TITLE
How to send debug output to stdout buffer instead of floating/popup window?

### ISSUE THREAD

**Issue by guilhermedallanol** [liquidz/vim-iced#413]
Hey there!

Instead of having the result of the debug like this (floating/popup window?):

![image](https://user-images.githubusercontent.com/861870/171201395-88602474-2381-4f02-90d6-bf762eb343c5.png)

How can I make it to be printed to the Stdout buffer, [like in this video](https://twitter.com/uochan/status/1034404572368842752)?

Thanks!

**Comment by liquidz** [comment]
@guilhermedallanol The video behavior is from an early, older version.

What is your purpose for which you'd like to print debugging results to the Stdout buffer?
If you want to see histories of debugging results, [vim-iced-fern-debugger](https://github.com/liquidz/vim-iced-fern-debugger) may be helpful.

**Comment by guilhermedallanol** [comment]
Oh, the problem in my end is that the floating/popup window is too small for some schemas that I have. That big schemas block me from seeing the rest of the information. If I had this in the buffer I would be able to scroll down and see all information.

I tried the fern debugger but I kept getting the sidebar for browsing the values and wasn't able to see which line I was like I could in the default debugger (as we can see that the execution is on line 20 in the image I posted above).

**Comment by liquidz** [comment]
Thanks for your response!

I see.
Then, it may be good to create another debugger plugin to print results to Stdout buffer simply.

**Comment by liquidz** [comment]
I'll try it later.

**Comment by guilhermedallanol** [comment]
Awesome, thanks for that!

**Comment by liquidz** [comment]
@guilhermedallanol 
I've created for trial.
https://github.com/liquidz/vim-iced-stdout-debugger
Could you try this plugin?

**Comment by liquidz** [comment]
Feel free to reopen if you have any problems :)
