### ISSUE TITLE
QUESTION: cancel/abort evaluation or tests

### ISSUE THREAD

**Issue by geekingfrog** [liquidz/vim-iced#428]
Hello

Is there a way to abort a computation or a test? For example, if I run all tests in the current project but want to abort midway through, is it something possible?
From the doc it doesn't seems iced support that, not sure if nrepl can do it either (although it seems possible with emacs, so likely doable).

Cheers

**Comment by liquidz** [comment]
@geekingfrog How about `IcedInterrupt` command?
https://liquidz.github.io/vim-iced/vim-iced.html#%3AIcedInterrupt
It is mapped to `<Leader>eq` by default.

**Comment by geekingfrog** [comment]
Oh, I missed that one from the doc. All good then, thanks.
