### ISSUE TITLE
Spinner keeps spinning with iced_eval (neovim)

### ISSUE THREAD

**Issue by formsandlines** [liquidz/vim-iced#443]
After updating to the latest version of iced (3.12.3148), I experienced an issue with the newly added spinner which just keeps spinning for certain evaluation commands:

![iced-test](https://user-images.githubusercontent.com/47990878/189522494-ea0b1786-aaf7-4b29-b340-39867365cce5.gif)

My neovim version is 0.7.2 .

It happens with these operators:
`<Plug>(iced_eval)<Plug>(sexp_inner_element)`
`<Plug>(iced_eval)<Plug>(sexp_outer_list)`
The result is shown in the output on the bottom but the spinner remains near the expression.

These operators work fine and only show the evaluation result:
`<Plug>(iced_eval_outer_top_list)`
`<Plug>(iced_eval_last_outer_top_list)`
`<Plug>(iced_eval_visual)`
`<Plug>(iced_eval_in_context)<Plug>(sexp_outer_list)`

So maybe it has something to do with `iced_eval`?

Setting `keep_inline_result` to true/false does not change the spinning behaviour.

**Comment by liquidz** [comment]
@formsandlines Thanks for your reporting!
Hmm, I could not reproduce the problem in my environment...
Is the problem reprodusable with the minimal configuration?
https://liquidz.github.io/vim-iced/#minimal_configuration

**Comment by formsandlines** [comment]
Okay, so I was not able to reproduce it with the minimal configuration either…

I just found out that one setting in my init file caused the problem:
`set clipboard=unnamed`

It is the same with `unnamedplus`.

`<Plug>(iced_eval)<Plug>(sexp_inner_element)` conveniently yanks the result, so I believe this may be the source. I like to use my system clipboard as the default register, so I hope this can be fixed somehow?

**Comment by liquidz** [comment]
@formsandlines Thanks for your confirmation!
OK. I'll try clipboard option to reproduce the problem tomorrow.

**Comment by liquidz** [comment]
@formsandlines I could reproduce the problem with `set clipboard=unnamed`. Thanks!
Just released fixed version(3.12.3153), so could you try?

**Comment by formsandlines** [comment]
Perfect! It works with `<Plug>(iced_eval)<Plug>(sexp_inner_element)` and `<Plug>(iced_eval)<Plug>(sexp_outer_list)`
for both `clipboard=unnamed` and `clipboard=unnamedplus`.

Thanks for fixing it!
