### ISSUE TITLE
Neovim 0.8.0: popup window never closes

### ISSUE THREAD

**Issue by sheluchin** [liquidz/vim-iced#447]
Hi, @liquidz.

It looks like on the newest stable release of Neovim the popup notification window never closes. New notifications produces additional popup windows as well. 

This release has been out for a little over a week now. I just wanted to test it out and see if there are any issues to report. There might be a few other small bugs, but I haven't tested it properly to report yet. Mostly vim-iced works well with 0.8.0!

Thank you for your work on vim-iced.

**Comment by liquidz** [comment]
@sheluchin Just released fixed version. [3.12.3161](https://github.com/liquidz/vim-iced/releases/tag/3.12.3161)
Could you try the latest version?

**Comment by sheluchin** [comment]
@liquidz Thank you, looks like it's a good fix.

**Comment by liquidz** [comment]
@sheluchin Sorry for late reply

> edit: one slightly related thing I notice is that if you're in the wrong REPL and try to evaluate a form, the Session error. You should be in a cljs session. message disappears instantly after displaying. It's gone too fast to read.

Hmm, I could not reproduce the problem in my environment.
I also tried with minimal configuration, but I could see the message.
https://liquidz.github.io/vim-iced/#minimal_configuration

**Comment by sheluchin** [comment]
@liquidz no worries about the timing of the replies! I appreciate you getting to it whenever you can.

It seems I cannot reproduce it anymore either. Not sure if it was a nightly build issue or something else. In the future I will test all reports against the minimal config. Thanks again!
