### ISSUE TITLE
How to close the test-buffer manually?

### ISSUE THREAD

**Issue by formsandlines** [liquidz/vim-iced#448]
Is there a way to close the test-buffer manually after it opened?

Sometimes it gets in the way and I want to close it to focus on my work, but it looks like there is no function or binding for that in vim-iced.

**Comment by liquidz** [comment]
@formsandlines Indeed.
There was  no way to close it, so I added `IcedTestBufferClose` command.
Could you try the latest version?

**Comment by formsandlines** [comment]
Works great, thanks for the quick addition!

I mapped it to `<localleader>tc` since I have the open command on `<localleader>to`. :)
