### ISSUE TITLE
Support for telescope.nvim

### ISSUE THREAD

**Issue by heralden** [liquidz/vim-iced#458]
There's a lot of useful functionality like `:IcedBrowseFunction` that requires [ctrlp.vim](https://github.com/ctrlpvim/ctrlp.vim), [fzf](https://github.com/junegunn/fzf) or [vim-clap](https://github.com/liuchengxu/vim-clap).

How about adding support for https://github.com/nvim-telescope/telescope.nvim which is fairly popular among neovim users?

**Comment by liquidz** [comment]
@heralden Thank you for your suggestion!

Sounds good :)
I'll implement it as a separate plugin just like `vim-iced-ddu-selector`.
https://github.com/liquidz/vim-iced-ddu-selector

**Comment by liquidz** [comment]
@heralden I've made it for trial.
https://github.com/liquidz/vim-iced-telescope-selector
Could you try?

**Comment by heralden** [comment]
Wow, that was quick!

Doing `:IcedBrowseFunction` in a clojure buffer returns:

```
Fetching...
E5108: Error executing lua ...gged/telescope.nvim/lua/telescope/builtin/__internal.lua:369: Vim(return):E909: Cannot index a special variable
stack traceback:
        [C]: in function 'cmd'
        ...gged/telescope.nvim/lua/telescope/builtin/__internal.lua:369: in function 'run_replace_or_original'
        ...nvim/plugged/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'key_func'
        ...e/nvim/plugged/telescope.nvim/lua/telescope/mappings.lua:350: in function 'execute_keymap'
        [string ":lua"]:1: in main chunk
Press ENTER or type command to continue
```

**Comment by liquidz** [comment]
@heralden Thanks for your confirmation!

Hmm, it works fine in my environment...
- neovim v0.8.3
- telescope.nvim v0.1.1

What versions are you using?

**Comment by heralden** [comment]
NVIM v0.8.0 with latest telescope.nvim. I actually tried it inside a long-running session and it worked. Then I relaunched nvim and I get the same error again. And then I realised I had forgotten to connect to the REPL 😄 - it works once I'm connected.

Thanks!
