### ISSUE TITLE
Evaluations should be echoed to the cmd REPL?

### ISSUE THREAD

**Issue by MarlonCorreia** [liquidz/vim-iced#469]
Hello, I hope you're doing good =]

I have a question about the start of the section 3.2 Results from the documentation:

> 3.2. Results
> 
> **The evaluation result is echoed on command-line** and displayed in a popup at the end of line. However, the displayed result is only the returned value, so for example, the contents output by println are not displayed.

To my understanding, it means that the evaluations done in the project should also be printed on the REPL opened with `iced repl` on the command line.

Mine does not work like that, and I'm not sure if it's a problem or a poorly interpretation of the documentation from my part.

**Comment by liquidz** [comment]
@MarlonCorreia 

> To my understanding, it means that the evaluations done in the project should also be printed on the REPL opened with iced repl on the command line.

No, it does not print on the REPL opened with iced repl on the command line.
In this context, command-line means [cmdline](https://vim-jp.org/vimdoc-en/cmdline.html) on Vim.

So if you set `cmdheight=0`, you cannot see evaluation results.

**Comment by MarlonCorreia** [comment]
Ohh, that makes sense. I'm still getting used to vim and the names of the sections! Thanks for the reply and clarification.
