### ISSUE TITLE
Code evaluation doesn't work on strings with ansi escape color codes

### ISSUE THREAD

**Issue by tastyminerals** [liquidz/vim-iced#471]
Trying to evaluate the following code block results in an error.
```clojure
(def ansi-styles
  {:red "\033[0;31m"
   :green "\033[0;32m"
   :blue "\033[0;34m"
   :reset "\033[0m"})
```
Hitting `<Leader>et` returns "Failed to find code" and inserts a 0 into next line below.
<img width="162" alt="Screenshot 2024-01-21 at 13 20 53" src="https://github.com/liquidz/vim-iced/assets/7676160/7ad0590a-e457-4ff8-91d1-b3e6921ac2bb">

Hitting `<Leader>ei` returns "Unable to resolve symbol: ansi-styles in this context.

Same behaviour for 
```clojure
(def ansi-styles
  {:red   "[31m"
   :green "[32m"
   :blue  "[34m"
   :reset "[0m"})
```

**Comment by liquidz** [comment]
@tastyminerals Thank you for your reporting!
Hmm, could you try to enable `matchit` plugin?
https://vim-jp.org/vimdoc-en/usr_05.html#matchit-install

**Comment by liquidz** [comment]
@tastyminerals Thanks!

>  I am using neovim

In my environment, neovim with [minimal configuration](https://liquidz.github.io/vim-iced/#minimal_configuration) works well.
It could be due to other plugins you are using 🤔 

I'm using neovim v0.9.5.
