### ISSUE TITLE
Disabling paredit

### ISSUE THREAD

**Issue by aceful** [liquidz/vim-iced#80]
Apologies if I overlooked something obvious, but is there a way to disable paredit mode? If not, would you consider adding an option for that?

**Comment by liquidz** [comment]
@aceful paredit mode is provided by [vim-sexp](https://github.com/guns/vim-sexp) which vim-iced depends on.
So how about to set `g:sexp_filetypes` like following?
https://github.com/guns/vim-sexp/blob/12292941903d9ac8151513189d2007e1ccfc95f0/doc/vim-sexp.txt#L655-L656

**Comment by aceful** [comment]
Perfect, thanks!

**Comment by mars0i** [comment]
Thanks for this--I wanted to turnoff paredit, too.  Runnijng `let g:sexp_filetypes=''` does disable it.

I'm a little bit confused, though.  It looks like setting `g:sexp_filetypes` to an empty string means that vim-sexp won't provide anything in Clojure source files, as if vim-sexp was not there.  Is paredit the only thing that vim-sexp provides? Will `let g:sexp_filetypes=''` affect the operation of vim-iced in other ways?

**Comment by liquidz** [comment]
@mars0i
As far as I saw [vim-sexp's help](https://github.com/guns/vim-sexp/blob/12292941903d9ac8151513189d2007e1ccfc95f0/doc/vim-sexp.txt#L655-L656), `let g:sexp_filetypes=''` leads disabling **only mappings**.
So vim-sexp is there without default mappings, and you can add mappings by yourself explicitly.

vim-iced uses vim-sexp via function, so `let g:sexp_filetypes=''` should not affect to vim-iced.

**Comment by mars0i** [comment]
Thanks @liquidz.  I see.  Great--that's good to know that it won't affect vim-iced.  Thanks very much for responding quickly. 

Ah, I understand now: The help file shows how to define all of the mappings that are normally enabled.  So I can copy and edit that example if I want.  Or leave it without the mappings.  OK, good.

(Do you think it would be worth including a line in the docs about disabling paredit?  I could submit a PR for it if that would be helpful.  I think this would go under the Tips section or the Configuration section, but I'm not what subsection.  Maybe in a new subsection--"Miscellaneous" or something else.)

**Comment by liquidz** [comment]
@mars0i It would be nice to have documentation.
PR is very welcomed! (Tips section may be good)

**Comment by mars0i** [comment]
OK, good.  I've written a draft but it's late here and I will look at it again tomorrow.  I should set up github pages site so I can see how it looks.
