### ISSUE TITLE
Eval visual selection

### ISSUE THREAD

**Issue by matthias-margush** [liquidz/vim-iced#87]
When I'm demoing code, I like to visually select what I'm eval-ing, so it's clearer on the screen. I didn't see anything like that yet in `vim-iced` (or if it's there, let me know.) I added this to my config based on the example in `:help :map-operator`. Would this be useful to have in `vim-iced`?

```
function! ClojureEval(type, ...)
	let sel_save = &selection
	let &selection = "inclusive"
	let reg_save = @@
	if a:0  " Invoked from Visual mode, use '< and '> marks.
		silent exe "normal! `<" . a:type . "`>y"
	elseif a:type == 'line'
		silent exe "normal! '[V']y"
	elseif a:type == 'block'
		silent exe "normal! `[\<C-V>`]y"
	else
		silent exe "normal! `[v`]y"
	endif

	call iced#nrepl#eval#repl(@@)

	let &selection = sel_save
	let @@ = reg_save
endfunction

vnoremap <silent> <buffer> (my key binding) :<c-u>call ClojureEval(visualmode(), 1)<cr>
```

**Comment by liquidz** [comment]
@matthias-margush Sounds good!

We have 2 function to evaluate codes.
* [iced#nrepl#eval#code](https://github.com/liquidz/vim-iced/blob/0.9.2/autoload/iced/nrepl/eval.vim#L75)
  * Evaluate codes in main(clj/cljs) session
* [iced#nrepl#eval#repl](https://github.com/liquidz/vim-iced/blob/0.9.2/autoload/iced/nrepl/eval.vim#L94)
  * Evaluate codes in REPL session

So we need 2 functions to evaluate visual selection.

**Comment by liquidz** [comment]
@matthias-margush I added `:IcedEvalVisual` and `:IcedEvalReplVisual` command.
https://github.com/liquidz/vim-iced/blob/0.10.1/doc/vim-iced.txt#L492-L500
https://github.com/liquidz/vim-iced/blob/0.10.1/doc/vim-iced.txt#L1369-L1370
