### ISSUE TITLE
See stacktrace when test throws exception?

### ISSUE THREAD

**Issue by matthias-margush** [liquidz/vim-iced#95]
Running:
```
(defn foo
  "I don't do a whole lot."
  []
  (throw (ex-info "Fix me, I fail." {})))

(deftest a-test
  (testing "FIXME, I fail."
    (is (foo))))
```

Results in a test summary (as expected):
```
;; a-test: FIXME, I fail.
expected: (foo)
  actual: clojure.lang.ExceptionInfo: Fix me, I fail. {}
```

Is there a way to inspect the exception and see the stack trace?

**Comment by liquidz** [comment]
@matthias-margush As a simple way, evaluating `(testing "FIXME, I fail." (is (foo))` will show stack trace in stdout buffer.
https://github.com/liquidz/vim-iced/blob/0.10.0/doc/vim-iced.txt#L252

With `:IcedTest...` commands, cider-nrepl will summarize the test results, so vim-iced cannot receive stack trace.

**Comment by matthias-margush** [comment]
👍 That works great, thanks!
