### ISSUE TITLE
--with-clj option to force clojure cli when there is a projec.clj

### ISSUE THREAD

**Issue by geraldodev** [liquidz/vim-iced#99]
Hi,

I'm evaluating the project. I'm favoring tools.dep for dependencies and avoiding lein as much as I can. The fulcro template (lein new fulcro app) creates project.clj but it's meant to be used just as a uberjar.
So I'm asking if you could create an option like --with-cljs but for tools-dep, this way the project.clj would be ignored and a n-repl server started (like when there is no project.clj and a deps.edn exists).

Regards,

Geraldo Lopes de Souza.

**Comment by geraldodev** [comment]
After opening this I realized that iced repl would not be the best way to use clj cli, because thre isn't a way to pass the aliases I want to load. -A:dev for example. Please delete the issue

**Comment by liquidz** [comment]
@geraldodev You can pass aliases like follows.
```
iced repl -A:dev
```
c.f. https://github.com/liquidz/vim-iced/blob/0.10.0/bin/iced#L131

Sorry for less documents.
I'll add documents and update `iced repl --help` outputs.

**Comment by geraldodev** [comment]
@liquidz Thank you for this tool !

I envy emacs for cider debugger since forever but cannot stand the complexity.

I've been wondering why vim has not produced good (updated) plugins for clojure.
I've tried to switch to code, but I'm kovisoft/slimv paredit addicted.

Now you bring vim-iced to the light.

Thank you !

**Comment by liquidz** [comment]
@geraldodev I added `--force-boot` and `--force-clojure-cli` options.
https://github.com/liquidz/vim-iced/blob/0.10.1/CHANGELOG.adoc#0101-2019-03-05
